### ISSUE TITLE
gie.c:roundtrip() UndefinedBehaviorSanitizer: float-cast-overflow with ans

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#1010]
An issue for #1009 

What is `ans` supposed to represent?  What range should it have?  And why is it allowed to be negative?  It would be great to have some range checking on ans and give a helpful message if the value was nonsensical.
```
third_party/proj4/tests/gie_fuzzer.cc:505:20: runtime error: 3.84808e+09 is outside the range of representable values of type 'int'
    #0 0x55c8e0b6898f in roundtrip(char const*) third_party/proj4/tests/gie_fuzzer.cc:505:20
    #1 0x55c8e0b6603c in dispatch(char const*, char const*) third_party/proj4/tests/gie_fuzzer.cc:766:49
    #2 0x55c8e0b65a31 in process_file(char const*) third_party/proj4/tests/gie_fuzzer.cc:242:19

SUMMARY: UndefinedBehaviorSanitizer: float-cast-overflow third_party/proj4/tests/gie_fuzzer.cc:505:20
``` 

```c
    static int roundtrip (const char *args) {
    // ...
    double ans = proj_strtod (args, &endp);
    ntrips = (int) (endp==args? 100: fabs(ans));
```

**Comment by kbevers** [comment]
So you can use `roundtrip` in gie files in two ways:

`roundtrip <n> <tolerance>` or `roundtrip <tolerance>`. So `ans` is either the number of roundtrips or the desired roundtrip tolerance. I guess the problem here is that the fuzzer is trying to do a number of roundtrips larger than what can be represented in an int.

A million roundtrips is probably more than enough to adequately test the numerical stability of forward/inverse conversion.

**Comment by schwehr** [comment]
BTW, It appears that the docs don't match the behavior described here: https://proj4.org/apps/gie.html

```
roundtrip <n> <tolerance>
Do a roundtrip test of an operation. roundtrip needs a operation and a accept command 
to function. The accepted coordinate is passed to the operation first in it’s forward mode, 
then the output from the forward operation is passed back to the inverse operation. This 
procedure is done n times. If the resulting coordinate is within the set tolerance of the 
initial coordinate the test is passed.

Example:

operation       proj=merc
accept          12 55
roundtrip       10000 5 mm
```
