### ISSUE TITLE
Document ellipsoid parameters

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/PROJ#1064]
The [source code for `pj_ell_set.c`](https://github.com/OSGeo/proj.4/blob/master/src/pj_ell_set.c#L36-L64) describes two ellipsoid size parameters ("a", "R"), five ellipsoid shape parameters ("rf", "f", "es", "e", "b"), and seven spherification parameters ("R_A", "R_V", "R_a", "R_g", "R_h", "R_lat_a", "R_lat_g").

Currently I see `+a`/`+b` documented in `usage/projections.rst`, and `+R` via `operations/options/R.rst`.

This task is to make a section and table of ellipsoid parameters in the docs (possibly somewhere under `usage/`).

**Comment by kbevers** [comment]
Yeah, there's a lot that is not described in the docs at the moment with regards to ellipsoids. Last year I gave a PROJ introduction to some of my colleagues which go in some more detail of how we handle ellipsoids. I have a few slides on the ellipsoids, starting [here](https://docs.google.com/presentation/d/1EYGeiYABCWQKvpx-FzgrNS5KnHTwGq-hWpOi3DcirCI/edit?usp=sharing).

A section on determining the shape of the Earth would be nice to have. Possibly as it's own page in the "Usage" chapter. That would allow us to simply link to that section when describing the individual projection parameters, say as part of `operations/options/R.rst` and/or `operations/options/ellps.rst`.

**Comment by RohitPingale** [comment]
@kbevers @mwtoews  Can I work on this issue? Also, the pj_ell_set.c file has been changed.

**Comment by kbevers** [comment]
Yes, you are most welcome to work on this! The relevant code has been moved to https://github.com/OSGeo/PROJ/blob/master/src/ell_set.cpp

**Comment by RohitPingale** [comment]
Sorry for the late update. please look into this [first draft documentation](https://github.com/RohitPingale/PROJ/blob/master/docs/source/usage/Ellipsoid.rst#ellipsoid--transformation)  and suggest the changes. I have added all info that is given in the [cpp file ](https://github.com/OSGeo/PROJ/blob/master/src/ell_set.cpp) and in the shared [presentation](https://docs.google.com/presentation/d/1EYGeiYABCWQKvpx-FzgrNS5KnHTwGq-hWpOi3DcirCI/edit#slide=id.g2977ac0210_0_6). 
other than that I put the generalized figure of ellipsoid transformation and added the definition of it. also, I tried to link the parameter table to the individual projection parameters as suggested by the @kbevers but It is not redirecting to the 
`operations/options/R.rst` and/or `operations/options/ellps.rst`

**Comment by kbevers** [comment]
@RohitPingale Thanks for giving this a go! I apologize for the late response, I was on vacation last week.

First of all, could you please open a pull request with your changes? That makes reviewing your work much easier.  Second, I don't understand what you mean by

> I tried to link the parameter table to the individual projection parameters as suggested by the @kbevers but It is not redirecting to the
operations/options/R.rst and/or operations/options/ellps.rst

Please elaborate on that when you open a pull request.

What is the source of the figure you've included? Are we actually allowed to use it?

A few things I'd like to see changed:

1. Describe the parameters using `.. option::` directives instead of using tables. This will keep things consistent within the docs. See https://github.com/OSGeo/PROJ/blob/master/docs/source/operations/options/ellps.rst for an example.
2. Add the new documentation page to `docs/source/usage/index.rst`
3. Link to the new doc page from `docs/source/operations/options/ellps.rst`

**Comment by imshuv** [comment]
I want to work on this issue can someone guide me through the process??

**Comment by kbevers** [comment]
@imshuv Someone already started working on this in https://github.com/OSGeo/PROJ/pull/2385 but they seem to have lost interest. My suggestion is to pull a copy of that branch and continue working on it based on my review comments in the pull request.
