### ISSUE TITLE
ubsan failure: "division by zero" in PJ_labard.c and PJ_somerc.c

### ISSUE THREAD

**Issue by DanielGuoVT** [OSGeo/PROJ#1126]
Hi there, 

I got "division by zero" runtime errors when testing proj.4 library with our fuzzing tool.
Here is the link to the test driver, test input, and error information:
https://github.com/DanielGuoVT/fuzzer_runtime_errors/tree/master/proj4

The found errors: 
input1 ==> PJ_labard.c:115:17, runtime error: division by zero
input2 ==> PJ_somerc.c:83:58: runtime error: division by zero
           ==> PJ_somerc.c:49:53: runtime error: division by zero

Anybody willing to take a look at this issue?

Thanks,
Daniel.

**Comment by kbevers** [comment]
If you can clean the examples up so they are a bit simpler to reproduce (preferable with one of the command line apps) I can take a look at what's going on.

Are you running this on the master branch close to HEAD?

**Comment by rouault** [comment]
The division by zero in labard was fixed per b30ed5cba50688cea9ac2af90855177f84efea5a
And with new checks when setting up ellipsoid parameters, the huge value of the e= parameter that caused Q->c = sqrt (1 + P->es * cp * cp * P->rone_es); to be 0 in the setup of somerc is now rejected.
So I believe this issue is now fixed
