### ISSUE TITLE
CMake build: sub-optimal generation of 'proj.db'

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1165]
Currently the cmake build of the data/ directory creates a temporary data/sql.all.in and the final data/proj.db files in the source tree, and not in the build tree. This would be ideally fixed.

Some improvements woud likely also be needed so that 'make test' / ctest consequently pass. It should probably involve PROJ_LIB to point to both the data/ of the source tree and the data/ of the build tree, now that it is supported ( ':' separator on Unix, ';' on Windows )

**Comment by kbevers** [comment]
Have we got any CMake gurus available to tackle this issue? @mloskot, @schwehr would either of you be willing to take a look at this?

**Comment by schwehr** [comment]
I'm 120% on GeoTools for a while :(

**Comment by dg0yt** [comment]
Having `proj.db` and `all.sql.in` generated in the build tree looks easy. 

For testing, the data files which would normally be installed could also be copied to the build tree, so that PROJ_LIB would be just the single build tree data directory. Unless you really want to test the PROJ_LIB separator handling on the build system side, which can be get quite difficult across platforms...
