### ISSUE TITLE
WKT CONCATENATEDOPERATION with STEPS in inverted order

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1197]
Following today OGC CRS SWG meeting, there will be likely an extension to the CONCATENATEDOPERATION to support constructs like CONCATENATEDOPERATION[SOURCE_CRS[A],TARGET_CRS[C],STEP[A,B] and STEP[C,B]] (pseudo WKT), meaning that the second step must be actually reversed

**Comment by busstoptaktik** [comment]
So this is akin to the PROJ `+inv` syntax?

* * *

If I understand it correctly, the transformation code must do pattern matching between `source_crs(C)` of the `step[...]`, and the `target_crs(C)` of `concatenatedoperation[...]`, to derive whether this step is to be taken in the forward or reverse direction.

This is AOK in cases where the concatenation consists of two steps only, and I suppose that it will work for multi-step operations too, by looking at `targetcrs/sourcecrs` of the surrounding steps. But it will get complex, since one must then iteratively keep track of which direction the surrounding steps have been assigned.

It will get quite hairy to read that kind of stuff, because it is impossible to see from the step alone whether it is considered forward or reverse.

It would probably have been a better solution to introduce either a modifier (like the PROJ `+inv`), or a specific keyword for reverted steps.

Since it is the reverse of a `STEP`, the name `PETS` would be an obvious choice.

* * *

Also, this relates directly to ISO 19162, which is currently in DRAFT status, but with the voting ongoing. Any chance this will make it into the ISO version of the OGC material? It would probably mean that one should vote "yes, with comments" to support the inclusion of this work?

**Comment by busstoptaktik** [comment]
> it is more a workaround 

s/workaround/horrible kludge/
:-)
