### ISSUE TITLE
Resolve differences with PJ objects created with proj_create versus PJ objects created with proj_create_from_user_input

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1214]
PJ object created with `proj_create()` do not play well with the other functions that used to have the proj_obj namespace (i.e. objects created with `proj_create_from_user_input()`).

Also, PJ objects created with `proj_create_from_user_input()` do not play well with functions that were meant to be used with PJ objects created with `proj_create()`.

It would be good to merge this behavior when/if it makes sense.

Also, a for reference: https://github.com/OSGeo/proj.4/pull/1208#issuecomment-450754124

**Comment by kbevers** [comment]
What are the discrepancies between the `proj_create`-style `PJ`'s and the `proj_create_from_user_input`-style `PJ`'s?  What will it bridge the gap?

Was it a mistake to merge `PJ` and `PJ_OBJ` into one type?

**Comment by rouault** [comment]
- PJ objects create with proj_create() have their iso_obj member set to NULL so all functions of c_api.cpp will return an error when called on such objects
- Most PJ objects created by proj_create_from_user_input() or other function of c_api.cpp have all the member of PJconst set to 0 / nullptr, except the iso_obj member. Consequently PROJ 5 proj.h functions will return garbage / error out. The only exception to this is when the iso_obj object is of type CoordinateOperation and has a PROJ string representation, in which case a fully valid PJ object is returned having both the 'traditional' member and iso_obj members set

> What will it bridge the gap?

I've considered this a bit this morning. A first idea would be to redirect proj_create() onto proj_create_from_user_input() when this is possible, but there are some subtelties. For example in GDAL, importFromProj4("+proj=longlat +datum=WGS84") would create a CRS with longitude, latitude degree coordinate system, and proj_create_from_user_input() does the same. So the PJ* object that corresponds to this would expect degrees. Whereas proj_create("+proj=longlat +datum=WGS84") expects radians.

> Was it a mistake to merge PJ and PJ_OBJ into one type?

I was midly enthousiastic to be honest. This enables further enhancements though in case we have inspiration on how to do it.

**Comment by kbevers** [comment]
> So the PJ* object that corresponds to this would expect degrees. Whereas proj_create("+proj=longlat +datum=WGS84") expects radians.

For #1205 I have been looking into splitting `PJ_IO_UNITS_ANGULAR` into `PJ_IO_UNITS_RADIANS` and `PJ_IO_UNITS_DEGREES`. I haven't spend too much time on this yet but it shouldn't be too difficult to do. If I understand correctly, most of the problem would go away although the users of the API would still have to use `proj_angular_output()` to check if the output should be converted from radians to degrees (`proj_angular_output()` should only return true if output units are `PJ_IO_UNITS_ANGULAR`). We could also go a step further and require that degrees are used instead of radians from version 6 an onwards.

**Comment by snowman2** [comment]
>importFromProj4("+proj=longlat +datum=WGS84") would create a CRS with longitude, latitude degree coordinate system, and proj_create_from_user_input() does the same. So the PJ* object that corresponds to this would expect degrees. Whereas proj_create("+proj=longlat +datum=WGS84") expects radians.

Do you think it would be a good idea to unify the behavior of `proj_create()` and `proj_create_from_user_input()`? I can guarantee users will be really confused to have one expect degrees and the other radians as it is a hidden difference that will be hard to find if you have not run into this before. What are your thoughts on removing `proj_create()` entirely and just using `proj_create_from_user_input()` as the `proj.4` way to create a projection and have some of the functionality within `proj_create()` added to `proj_create_from_user_input()` so the PJ object returned is fully initialized?

**Comment by snowman2** [comment]
> We could also go a step further and require that degrees are used instead of radians from version 6 an onwards.

I like the idea of this. It definitely simplifies things. Are there any drawbacks to this (besides the code changes required)?

**Comment by rouault** [comment]
The issue with angular units goes beyond just the simple +proj=longlat case:  "+proj=utm", "+proj=hgridshift", and all other operations that expect/return angles use radians which is the natural unit from a mathematical point of view. When chaining operations, we wouldn't want to do many deg to rad and rad to deg conversions 
One could consider that proj_create() is for low-level operations for very advanced users that know the syntax of PROJ operations, and the new ISO19111 functionality offer a higher level view.

**Comment by rouault** [comment]
> For #1205 I have been looking into splitting PJ_IO_UNITS_ANGULAR into PJ_IO_UNITS_RADIANS and PJ_IO_UNITS_DEGREES

What about other angular units, like grad, or even user defined units ?

> Me too. For the last ~30 years PROJ has expected angular coordinates in radians. It is going to affect everyone that has been using a PROJ version before 6.0

Only users of PROJ 5 proj.h API, no ? pj_transform() shouldn't be affected if this is done only at proj_trans_*() level.

> I would keep radians internally and simply do the DEG2RAD and RAD2DEG conversions first/last thing in the proj_trans_*() function family. Of course only where the underlying pipeline expects or returns radians. Would that work for you @rouault ?

I guess that can work. Early adopters of PROJ 5 proj.h API will likely not appreciate it though... If we are to break PROJ 5 new API, there are likely other misceaneleous things to consider: like not exposing the `proj` function pointer member of struct PJ_LIST, not attaching a PJ_CONTEXT to a PJ itself but require PJ_CONTEXT to be passed explictly to each API call (which I've done in the C API of the ISO-19111 code since that allows to have per-thread context and PJ objects to be independent of the thread that create them), etc etc. But we shouldn't discuss that in this ticket

**Comment by snowman2** [comment]
> If we change to expect degrees a naive switch of pj_transform to proj_create_crs_to_crs/proj_trans will not go so well. 

I think it already expects degrees. I had to change pyproj such that the input is degrees to the `proj_trans` and `proj_create_crs_to_crs`/`proj_trans_generic` functions to preserve the existing behavior.

Side note: Is this correct [here](https://github.com/OSGeo/proj.4/blob/3ea468222fdabdae3aa5b47439d6b3bfb0a93c8e/src/apps/proj.cpp#L164)?

**Comment by snowman2** [comment]
Never mind, I was incorrect about that last statement about the input being degrees.

**Comment by rouault** [comment]
I'm still not sure what to do about this issue. I'm circling around between trying to implement something or setting back because of various obstacles.

1) There's ambiguity about the nature of a PROJ string. Even before PROJ 5, a PROJ string could be interpreted differently according to the context.
Depending of if you used it with pj_fwd() or pj_transform(), there was differences. With pj_fwd(), it was meant as the conversion of a projected CRS (speaking in ISO-191111 parlance). With pj_transform(), it was meant as a way of expressing a CRS (the +pm keyword for example was honored only by pj_transform(), and the +datum, +towgs84, +nadgrids etc concepts were also introduced to add early-binding capabilities and only makes sense in the context of CRS to CRS transformations).
With PROJ 5 and the introduction of pipelines, in the proj_trans() case, a PROJ string can be seen as a fullyfledged ISO19111 coordinate operation, with various conversion and transformation methods, potentially a concatenated operation.
In my ISO-19111 work, the ingestion of a PROJ string is analyzed depending of various heuristics, with a priority to understand it as a CRS, as was done in GDAL with OSRImportFromProj4(). I chose to design a PROJ.5 format to resolve some ambiguities about the export of CRS as PROJ string, mostly regarding about axis order and units, and export those CRS as a pipeline with the following conventions:
```
     *
     * <ul>
     * <li>For PROJStringFormatter::Convention::PROJ_5 (the default), return
     * strings that generally express PROJ.5 pipelines.
     * <ul>
     * <li>For a crs::GeographicCRS, returns a string expressing the
     * transformation from geographic coordinates expressed in radian with
     * longitude, latitude order, and with respect to the international
     * reference meridian, into geographic coordinates expressed in the units
     * and axis order of the CRS, taking into account its prime meridian.</li>
     * <li>For a geocentric crs::GeodeticCRS, returns a string expressing the
     * transformation from geographic coordinates expressed in radian with
     * longitude, latitude order, and with respect to the international
     * reference meridian, into geocentric coordinates.</li>
     * <li>For a
     * crs::ProjectedCRS / crs::DerivedGeographicCRS / crs::DerivedProjectedCRS,
     * returns a string expressing the transformation from the base CRS to the
     * CRS</li>
     * <li>For a crs::BoundCRS, throws a FormattingException.</li>
     * <li>For operation::CoordinateTransformations, returns a PROJ
     * pipeline.</li>
     * </ul>
     *
```
So
```
$ src/projinfo "+proj=longlat +datum=WGS84"
PROJ string:
+proj=pipeline +step +proj=longlat +ellps=WGS84 +step +proj=unitconvert +xy_in=rad +xy_out=deg

WKT2_2015 string:
GEODCRS["unknown",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]],
        ID["EPSG",6326]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8901]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]
```

If you feed the input string "PROJ 4 style" (+proj=longlat +datum=WGS84) or the output "PROJ 5 style" (+proj=pipeline +step +proj=longlat +ellps=WGS84 +step +proj=unitconvert +xy_in=rad +xy_out=deg) string in proj_create() and use proj_trans(), you'll get different results

So if we redirect proj_create() to proj_create_from_user_input(), I'm not sure if we should use the input or output string as the internal pipeline... Maybe it was a bad idea to design this PROJ.5 style improvement, but even before, in GDAL, "+proj=longlat" was interpreted as meaning degree angular unit for the coordinate system of the CRS, whereas with pj_fwd/pj_transform, it was radian.

2) But more fundamentally, a CRS is a CRS, not a coordinate operation. If you create a PJ object with proj_create('EPSG:32631'), no standard dictates the coordinate operation you might do on it. Basically my PROJ 5 format was an attempt to define rules, but that's just personal taste.

**Comment by kbevers** [comment]
Okay, I have given this some thought over the last two days. I *think* that most of the problems we're facing here can be solved by distinguishing between coordinate operation objects and descriptive objects (e.g. CRS's, datums, ellipsoids, etc). Although there's a risk of creating other problems...

Consider splitting the current `PJ` object into `PJ` for operations and `PJ_DESCR` for anything that doesn't describe a coordinate operation. Operations would then be created something like this:

```
/* Don't pay attention to the names, */
/* I am sure better ones can be thought of this is just for the sake of illustration. */

PJ_CONTEXT* ctx = proj_context_create();

PJ* P1 = proj_create(ctx, "+proj=pipeline +step ...");

/* or */

PJ_DESCR* source_crs = proj_create_descr(ctx, "+proj=latlong +datum=WGS84");
PJ_DESCR* target_crs = proj_create_descr(ctx, "EPSG:25832");
PJ* P2 = proj_create_descr_to_descr(ctx, source_crs, target_crs, 0);
```

This way we force the user of the API to decide if a projstring is describing a CRS or an operation. If you pass it to `proj_create_descr` it will be treated one way and if you pass it to `proj_create` it will be treated another way. With this we could also have a way to distinguish between operation EPSG codes and CRS EPSG codes: `proj_create("EPSG:xxx")` would instantiate the operation xxxx and `proj_create_descr("EPSG:xxxx") would instantiate the CRS xxxx.

I would probably deprecate `proj_create_crs_to_crs` to avoid confusion. Or it could be changed to take `PJ_DESCR` objects instead of strings which would be nicer but the downside is that the API is changed.

I think that the above from a user perspective is much easier to understand than trying to communicate how `PJ` object can be basically anything. Adjusting the current C API to include the above is probably not too difficult but it may be necessary to add more functions, for instance `proj_create_from_wkt` could produce either a `PJ` or a `PJ_DESCR` and that is not going to work so that should probably be split into `proj_create_from_wkt_operation` and `proj_create_from_wkt_descr` or something like that. I suspect that will be the case for several other functions.

@rouault what do you think about this approach? I am sure there's a bunch of things that I haven't considered but it seems to me that we can overcome the differences between PROJ.4 and 5 style strings.

**Comment by rouault** [comment]
> @rouault what do you think about this approach?

Hum, sounds a bit like the situation before I merged PJ_OBJ in PJ, no ? :-(
I'd note that there are also not only CRS and operation EPSG objects, but also datum, ellipsoid, etc. Actually proj_create_from_user_input() can accept strings like "urn:ogc:def:ellipsoid:EPSG::7030"
And if you have different PJ and PJ_DESCR types then a number of methods like proj_get_name(), proj_get_area_of_use(), proj_get_id_code(), etc etc should be duplicated. Sounds messy.
I'm afraid I've no more energy/motivation to do such a change myself.

**Comment by kbevers** [comment]
> Hum, sounds a bit like the situation before I merged PJ_OBJ in PJ, no ? :-(

Really? In that case I have misunderstood it completely! A `PJ_OBJ` could also represent a coordinate operation, yes?

> I'd note that there are also not only CRS and operation EPSG objects, but also datum, ellipsoid, etc. 

Yes. They are all of a descriptive nature as well, although they may not all be useful for the construction of transformations in all situations.

> And if you have different PJ and PJ_DESCR types then a number of methods like proj_get_name(), proj_get_area_of_use(), proj_get_id_code(), etc etc should be duplicated. Sounds messy.

I am afraid whatever we do it is going to be messy. I am simply searching for the least messy way forward. I don't claim to have found it yet :-)

> I'm afraid I've no more energy/motivation to do such a change myself.

I completely get that. I know you are running a tight schedule. I hope that you know that I am not going on about this to piss you of - I am merely concerned about doing the new functionality as best as possible.

**Another suggestion**: PROJ.4-style strings are only interpreted as CRS descriptions when passed into `proj_create_crs_to_crs` and `pj_init*` (possibly others?) and otherwise treated as a coordinate operation. We (Well... I, I guess) write a section in the docs that explain the two types of proj-strings and which one to use where. Lastly, we put out a note saying that PROJ.4 style descriptive proj-strings are deprecated and the use of them will be prohibited in PROJ 7. When we start work on PROJ 7 we will be rid of that particular nuisance once and for all. Is this a better approach?

**Comment by rouault** [comment]
> Really? In that case I have misunderstood it completely! A `PJ_OBJ` could also represent a coordinate operation, yes?

Yes a PJ_OBJ could also represent a coordinate operation. This is not a completely revert, but not far though.
A coordinate operation is also "descriptive" when instantiated from EPSG or WKT.

> I am merely concerned about doing the new functionality as best as possible.

Yes, but I'm afraid we hit issues with backward compatibility, and we cannot completely get rid of the past (see below), and having both backward compat and super clean design might not be doable.

>  PROJ.4-style strings are only interpreted as CRS descriptions when passed into proj_create_crs_to_crs and pj_init* (possibly others?) and otherwise treated as a coordinate operation
> Lastly, we put out a note saying that PROJ.4 style descriptive proj-strings are deprecated and the use of them will be prohibited in PROJ 7

This is not possible. PROJ.4 strings to express CRS are part of metadata of many file formats, so they will have to be supported forever (software might be changed, but existing data not). Or I'd have to reimplement that again in GDAL itself, which, in addition to extra development, would be a design error from my point of view, since after the merge of my gdalbarn GDAL branch, GDAL will get/set PROJ strings from/into PROJ in a completely opaque way.

-------

Something I've thought to avoid having two different create() method could be to have a "+type=crs" in a PROJ string to distinguish between the CRS and operation cases.

**Comment by kbevers** [comment]
> Yes, but I'm afraid we hit issues with backward compatibility, and we cannot completely get rid of the past (see below), and having both backward compat and super clean design might not be doable.

Oh, I am quite certain that it is not doable, but limiting unclean design as much as possible is desirable I think. I expect this API to stay around for a long time! It is very likely though that you have already created the most clean version of this API that can be created while also honouring the past.

> This is not possible. PROJ.4 strings to express CRS are part of metadata of many file formats, so they will have to be supported forever (software might be changed, but existing data not). Or I'd have to reimplement that again in GDAL itself, which, in addition to extra development, would be a design error from my point of view, since after the merge of my gdalbarn GDAL branch, GDAL will get/set PROJ strings from/into PROJ in a completely opaque way.

Yeah, I keep forgetting about the real world... You are right, we are stuck with the bagage from the past for many years to come. I don't like it one bit but that is not worth much.

> Something I've thought to avoid having two different create() method could be to have a "+type=crs" in a PROJ string to distinguish between the CRS and operation cases.

This might be the best possible solution. Would you add other +types as well? Otherwise it could just be a flag `+crs`. 
There are also indirect indications of wether a string is a CRS: `+datum`, `+towgs84`, `+nadgrids`, `+geoidgrids` and `+axis`. Conversely a proj-string is *not* a CRS if `+proj=pipeline` is present in it. Unfortunately this is not enough to uniquely identify if a proj-string is a CRS or not, but it goes a long way I think.

**Comment by rouault** [comment]
> Would you add other +types as well

Not sure, but I feel like a boolean flag should be reserved for something that is clearly boolean, like +inv (there are only 2 directions: forward or inverse). If something is not a crs, it might be a lot of different things. Using +type= would make us more free to extend in the future.

> `Conversely a proj-string is *not* a CRS if `+proj=pipeline` is present in it

Hum, with my PROJ.5 format, the pipeline syntax is used to express axis order or units. See example in https://github.com/OSGeo/proj.4/issues/1214#issuecomment-451681404. We might still decide it was a bad idea and consider something else (I'd be happy implementing such a change). I chose the pipeline approach as it seemed to be the "modern" way, but using axis= would have been equally doable. The only thing actually missing is a "+angunits=deg" to explicitly specify the angular unit.
Or ... more radical way ... I'm wondering if we really need a PROJ.5 syntax to express CRS. PROJ strings will always be a more ambiguous solution than WKT for this. So we could probably just ditch the PROJ.5 syntax idea. Was perhaps over-engineering.

**Comment by kbevers** [comment]
> Not sure, but I feel like a boolean flag should be reserved for something that is clearly boolean, like +inv (there are only 2 directions: forward or inverse). If something is not a crs, it might be a lot of different things. Using +type= would make us more free to extend in the future.

Good point. I agree, just wanted to be sure I understood where you were going.

> Or ... more radical way ... I'm wondering if we really need a PROJ.5 syntax to express CRS. PROJ strings will always be a more ambiguous solution than WKT for this. So we could probably just ditch the PROJ.5 syntax idea. Was perhaps over-engineering.

To be honest this seems like the best way forward. WKT is better at describing CRS's and we will still have the PROJ.4 style CRS descriptions for the cases where WKT is not suitable. I guess this would also reduce the amount of code somewhat?

**Comment by snowman2** [comment]
If y'all don't mind, I will add my opinion.

I think that having the CRS and proj functionality separate is very nice for clarity. It was easy for me to piece together the functionality when the PJ_OBJ existed. I think taking it a step further to separate the functionality could be an option for a clean solution.

What are your thoughts on having a crs.h and a proj.h to further separate the functionality? Also, instead of going to a PJ_OBJ, you could rename it to CRS.

I did that in the new pyproj design [here](https://github.com/snowman2/pyproj/tree/gdalbarn/pyproj). You can see examples of usage in the docstrings as well as in this [issue](https://github.com/jswhit/pyproj/issues/152).

**Comment by kbevers** [comment]
@rouault with your changes in #1217, are we any closer to resolving this? Is there more that can be done at the moment to unify the two ways of creating `PJ` objects?

**Comment by rouault** [comment]
Proposed plan:
- suppress proj_create_from_user_input() and proj_create_from_proj_string()
- proj_create() will accept all the potential strings handled by proj_create_from_user_input() (ie PROJ strings, WKT, or URNs). For PROJ strings, it will instanciate a coordinate operation object, unless +type=crs is added. "+proj=longlat +ellps=WGS84" will so be a coordinate operation expecting and outputing radians, whereas "+proj=longlat +ellps=WGS84 +type=crs" will describe a geographic CRS with degree units
- proj_create_crs_to_crs() will automatically add +type=crs if not found (and so cs2cs will do, since it uses proj_create_crs_to_crs())
- (note for myself: GDAL OGRSpatialReference will automatically add +type=crs too)
- exportToProjString() from a CRS object should add +type=crs. Will break many ISO19111 tests
- projinfo "+proj=utm +zone=31 +ellps=WGS84" , using underneath the new proj_create() will instanciate a coordinate operation, and not a CRS, if +type=crs is not added ?? Or, perhaps more user friendly, as there is a -k crs/operation flag already when resolving EPSG codes, and -k crs is the default, perhaps we should automatically add +type=crs unless -k operation is specified (and the current proj_create_from_user_input() defaults to interpreting as a coordinate operation if it cannot understand  the string as a CRS) ?
- pj_init() combined with pj_transform() should still work as in the past, that is expect radians for +proj=longlat (normally, nothing particular to do since +type=crs will not be passed when using those older interfaces)

Does that sound useful / more user friendly ? (hoping they aren't fundamental issues I haven't spotted)
I'd note that actually does not solve @snowman2 initial remark about objects creating with proj_create() (ie PROJ strings expressing coordinate operation) not playing well with new proj_() functions I've added.

**Comment by busstoptaktik** [comment]
> Does that sound useful / more user friendly ? (hoping they aren't fundamental issues I haven't spotted)

Sounds awesome if it can be made to work! The Grand Unified Handler of all geospatial reference system and coordinate operation notations...

> I'd note that actually does not solve @snowman2 initial remark about objects creating with proj_create() (ie PROJ strings expressing coordinate operation) not playing well with new proj_() functions I've added.

So the long term solution (PROJ 7? 8? 9?, i.e. whenever someone finds time/funding/motivation) is to attempt to translate PROJ notation to WKT2 and unify everything?

(although that will probably require a rewrite of the proj.h PJ introspection functions).

> projinfo "+proj=utm +zone=31 +ellps=WGS84" , using underneath the new proj_create() will instanciate a coordinate operation, and not a CRS

No firm opinion on this, but at least this would be consistent with the action of other PROJ command line tools (proj, cs2cs, cct)

**Comment by rouault** [comment]
> attempt to translate PROJ notation to WKT2 and unify everything?

I don't think that's doable with a meaningul WKT2 representation. A PROJ pipeline chains different coordinate operations but you don't know which CRS are used as inputs / outputs, whereas a ISO-191111 coordinate operation require input/output CRS for each step of a concatenated operation.

**Comment by busstoptaktik** [comment]
> I don't think that's doable with a meaningul WKT2 representation

My current stance is that this is a bug (or at least a too restrictive domain of definition) in WKT2, and I'll do my very best to either remedy the bug (during next revision cycle of ISO-19111 and friends) or be proven wrong and rest my case, at least having obtained a higher level of geospiritual insight :-)

But obviously it is also an (easily removable) limitation of the PROJ notation that we cannot explicitly define the I/O CRS.

In the parameter files of the [Nordic Geodetic Commission](https://github.com/NordicGeodesy/NordicTransformations), @kbevers worked around this limitation by introducing the convention that, when invoked in the forward direction, all transformations go from the "current system" (e.g. ETRS89) to the system specified in the angle bracketed \<label\> of the parameter file section.

**Comment by rouault** [comment]
PR #1223 implements https://github.com/OSGeo/proj.4/issues/1214#issuecomment-454411774
