### ISSUE TITLE
Belgium Lambert 72 - hBG03 to WGS-84

### ISSUE THREAD

**Issue by richy46** [OSGeo/PROJ#1227]
I have a question regarding Belgium datum conversion.
I am trying to convert from WGS-84 to Lambert72/hbg03 heights. I have a hbg03 gtx file but this contains WGS-84 geographical coordinates and the geoid heights above WGS-84 (the GTX contains heights between +40 and +46 meters).

my source datum is:
 +proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 
+lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl
 +towgs84=-106.869,52.2978,-103.724,0.3366,-0.457,1.8422,-1.2747 
+geoidgrids=hbg03.gtx +units=m +no_defs 

so my target datum is
+datum=WGS84 +no_defs +proj=longlat

my source point is:
E 220000
N 181600
H 25.00 m

my target point should become:
50.940462128 deg
5.364723438 deg
68.183 m
But I get for the height: 111.594
Height at this point from gtx = + 43.183

So obviously wrong, and this is of course because the gtx file that is provided with the source contains not the heights ref to that source (beligan datum) but ref wgs.  My question is how to define the proj4 transformation correctly?

**Comment by rouault** [comment]
@kbevers I can reproduce this (using egm96_15.gtx for conveniency) with cs2cs with PROJ 5.2.0 or in master (in master you need to use EPSG:4979 as target otherwise the vgridshift part is dropped).

I believe this is an issue that has been reported several times in past years, and we've always considered to do the right thing, but I've some doubts.

I think the core of the issue is that we should only apply Helmert for the 2D part. EPSG publishes method like "Position Vector transformation (geog2D domain), EPSG method code 9606" / "Coordinate Frame rotation (geog2D domain), EPSG method code 9607" where the Z value has no real significance (see http://www.epsg.org/Portals/0/373-07-2.pdf?ver=2018-10-12-153840-577 page 147 "Step 5: Because the source coordinates were 2D, using method 2.2.4 the target system ellipsoidal height is dropped and the results treated as a geographic 2D coordinate reference system". 
The values of the towgs84 clause used here, except the precision of values and CF vs PV convention, the ones of the EPSG:15928 coordinate operation: https://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:coordinateOperation:EPSG::15928, which is a "Coordinate Frame rotation (geog2D domain)".

Currently we use the transformed ellipsoid height after the cart -> helmert -> inverse_cart chain, but we should probably preserve the original Z value before doing the initial cart step. I'm not sure how we can fix this...  Should we have a helmert_geog2D method that would do internally what we do currently but restore the Z value at the end ?

**Comment by kbevers** [comment]
I've been pondering the same thing for some time actually. I have run in to a similar thing while trying to reproduce Greenlandic legacy transformations in PROJ.

What is needed, really, is a way to push a component of a coordinate (z in this case) from one step in a pipeline to another and overriding the value in the destination step. Basically a stack that can be pushed and popped between steps. For instance

```
+proj=pipeline 								# 12 56 33 (z-stack=empty)
+step +proj=latlong +push=z					# 12 56 33 (z-stack=33)
+step +proj=cart +ellps=GRS80				# 3496741.6437    743255.3808  5264469.5943 (z-stack=33)
+step +proj=helmert +x=10 +y=20 +z=30 		# 3496751.6437    743275.3808  5264499.5943 (z-stack=33)
+step +proj=cart +inv +ellps=GRS80 +pop=z   # 12.0002802196   56.0000468751 33 (z-stack=empty)
+step +proj=hgridshift +grids=...			# 12.5002802196   56.4000468751 33 (z-stack=empty)
```

where both `+push` and `+pop` takes the value after the execution of the step and either adds or removes it from a stack kept internally in the pipeline memory. When `+pop`'ing a coordinate value it overwrites whatever is stored in the output from that step.

That's the best I have been able to come up with so far. Of course stacks for the other coordinate components should be available although I don't imagine those being utilized much. What I like about this approach is that it is a generic solution that can be used in many other scenarios we haven't thought of yet.

What do you think about that @rouault?

**Comment by kbevers** [comment]
> I guess this should be done in pipeline_forward_4d(), since the fwd of the push/pop step would lack a more general context where to push/pop the value(s) (each step only knows a XYZT)

Yes, that's why I proposed to `+push` and `+pop` as parameters for the pipeline operation. I agree that it would be better to have them as individual steps. It *is* doable if we introduce a parent/child relationship between a pipeline (parent) and its steps (childen). The stack memory is hosted by the parent `PJ`. This however has the potential of becoming a bit of a mess when pipelines are nested.

**Comment by kbevers** [comment]
> In your proposal, they would be parsed as parameters of the individual step, not the pipeline itself.

You don't get to decide that ;-) I would parse `+push` and `+pop` within the setup function of the pipeline operation. Probably in the same loop that parses `+step`'s. And then make sure to push/pop any values as the last thing in `pipeline_forward_4d()` etc. I don't see why that shouldn't be possible. I will admit that it is difficult to distinguish parameters that apply to the pipeline and the individual steps but that could be dealt with by using better names such as `+pipeline_push` or something similar.

> I don't really see an issue if a PJ would have a PJ* parent member. Nesting of pipelines shouldn't matter.

I am sure you are right. It is late, I am not at full brain capacity.

In any case, I think a stack on the pipeline is the way to go. If it is one way or the other isn't important to me.

**Comment by richy46** [comment]
Hi Thomas, The HBG03 grid is in geographical WGS-84 coordinates.

**Comment by kbevers** [comment]
@busstoptaktik 	I think your approach with a buffer containing all intermediate coordinates is good. Maybe something like (step numbers in angle brackets):

```
+proj=pipeline 								     # [0] 12 56 33
+step +proj=cart +ellps=GRS80				     # [1] 3496741.6437    743255.3808  5264469.5943
+step +proj=helmert +x=10 +y=20 +z=30 		     # [2] 3496751.6437    743275.3808  5264499.5943
# grap z from pipeline buffer step 0 (original input)
+step +proj=cart +inv +ellps=GRS80 +pipe_buf_z=0 # [3] 12.0002802196   56.0000468751 33
+step +proj=hgridshift +grids=...			     # [4] 12.5002802196   56.4000468751 33
```

We should be able to make this work in reverse as well. All the work will be made with `pipeline.cpp` for this. Reading the parameters in the setup and overriding the coordinate values with buffer values in the forward and inverse functions.

**Comment by rouault** [comment]
> but the correction grid for the Lambert projected coordinates is, if I read your figure correctly, in Lambert coordinates?

@busstoptaktik +geoidgrids= always proceed on working with geographic coordinates in the hard-coded steps of pj_transform(), and this was emulated although in the pj_fwd() / pj_inv() preparation steps.

-------

@busstoptaktik  I don't like very much referencing a pipeline step by number. This is rather error prone, and this prevents easily combining of pipelines (imagine you concatenate two pipelines). The push/pop syntax is more explicit on the intent.

**Comment by busstoptaktik** [comment]
> The push/pop syntax is more explicit on the intent.

Yes, but it enforces push/pop gymnastics when you need more than one previous result, and you must know whether steps further down the pipeline need it as well. It will be somewhat complex under all circumstances.

A different, and potentially more readable, approach could be to use a std::map, indexing the parameters by a string name. This would, however, require explicit expressing that an intermediate result should be stored, but it will make the intent even more clear.

**Comment by rouault** [comment]
@busstoptaktik  Something like ? :
```
+proj=pipeline
+step +proj=savecoord +z_as=z_saved		 # z_saved is a free name			
+step +proj=cart +ellps=GRS80				
+step +proj=helmert +x=10 +y=20 +z=30
+step +proj=cart +inv +ellps=GRS80
+step +proj=loadcoord +z_from=z_saved             # note: we could also allow numeric values, such as +z=123. Could potentially be useful on the time variable
+step +proj=hgridshift +grids=...	
```

**Comment by busstoptaktik** [comment]
> Something like 

@rouault: Yes, except that I assume that what we save is the entire PJ_COORD tuple, not individual parts of it, *AND* we typically will need to use the saved coordinate *together* with the "result so far". So rather:

    proj=pipeline
    step proj=save  name=bob
    step proj=cart +ellps=GRS80
    ...
    # this grid needs original coordinate to locate gridshift for transformed
    step proj=hgridshift use=bob  

Note: This does not limit the use case you presented, since we can have a

    proj=manipulate  take_z_from=bob

**Comment by busstoptaktik** [comment]
> And here, it looks like it only affects this step, but in practice this is no different than ...

It is different, since this hypothetical grid needs the original coord as input, but reads corrections that are applied to the coordinate provided through the pipeline. This case may happen, if I understand my retired colleague Karsten Engsager correctly, when  both the helmert shift and the deformations of the frame modelled by the grid shift, are large (or pathological), making it hard to reach convergence in the inverse case.

Obviously, the use=... and save=... parameters will only be supported for operations explicitly tailored to make use of it. Most cases will be handled as you indicate:

    step proj=load name=bob

or 

    step proj=load take_z_from=bob

(where I suppose the `load` operation has swallowed the functionality of  the stuff I put in the `manipulate` operation above).

The case you present simply throws away the Helmert shift, and applies the grid correction to the original coordinate.

**Comment by rouault** [comment]
> It is different, since this hypothetical grid needs the original coord as input, but reads corrections that are applied to the coordinate provided through the pipeline. The case you present simply throws away the Helmert shift, and applies the grid correction to the original coordinate.

OK, I now better understand your initial intent

It should be noted that pipelines that use those save/load/use functionality would be non-invertable.
Actually, even if we used the push/pop syntax that could be made invertable (the reverse of push is pop, and vice-verca), the Helmert  transformation with only keeping the 2D part is also non-round-trippable: forward operation followed by inverse operation will not lead to the original input

**Comment by busstoptaktik** [comment]
Yes, it's all quite hairy, so it's nice to have this opportunity to discuss the subject.

I *think* we once discussed having a notation for making different steps active in the forward case, resp. inverse case. This would make it possible to construct invertible pipelines even in the case of using intermediate result forwarding.

Actually, I think the most readable syntax would be to allow defining two entirely separate pipelines for each direction:

    proj=pipeline forward step ... step ... inverse step ... step ...

**Comment by kbevers** [comment]
Regarding invertable pipelines: Let's handle the cases that are simple (for instance using the push/pop model) and ignore the complex cases that require special treatment for forward and reverse transformations. At least from the viewpoint of the pipeline operation. Pipelines that require a different setup for the inverse operation can still be generated from the database by simply swapping what is the source and destination CRS - we don't need to make sure that a pipeline can be reversed. The ISO19111 code should be able to handle that, right?

**Comment by rouault** [comment]
> (for instance using the push/pop model)

So you would be in favor of having a push/pop model for now ?

> we don't need to make sure that a pipeline can be reversed. The ISO19111 code should be able to handle that, right?

The ISO19111 code does a lot of inverse() operations when creating ConcatenatedOperation to save coding (for example if you have code to deal with the situation where src=DerivedCRS, when you encounter dst=DerivedCRS, you can just call the previous code with inverted arguments and use the inverse() on it. See for example https://github.com/OSGeo/proj.4/blob/master/src/iso19111/coordinateoperation.cpp#L11304). But that works on CoordinateOperation objects, so you don't need to invert PROJ pipelines themselves.

The generation of the PROJ string is something that is defered to the exportToPROJString() method.

Not sure to have really understood your question and hoping not too add confusion...

***********

Now the question is: who want to tackle this and for what timeframe ? Do we need this absolutely in PROJ 6 ? I'm not sure if I've available bandwidth until PROJ 6 for new features (maybe, maybe not...)

**Comment by kbevers** [comment]
> So you would be in favor of having a push/pop model for now ?

I am +0 on whatever model someone is willing to implement. Several ways forward has been demonstrated now and I think all of them have some merit to them. If I were to implement it right now I think I would go with a push/pop model with a stack only able to contain one value (per coordinate dimension) at a time in order to limit the problem-space as much as possible.

> Not sure to have really understood your question and hoping not too add confusion...

I think you did. At least partially and I got the answer that I needed: Pipelines are inverted all the time so we should try to make that possible for as many use cases as possible, even the esoteric ones like this.

> Now the question is: who want to tackle this and for what timeframe ? Do we need this absolutely in PROJ 6 ? I'm not sure if I've available bandwidth until PROJ 6 for new features (maybe, maybe not...)

This is in the need-to-have department in my opinion. It can easily wait for 6.1. I expect to be quite tied up in non-PROJ work until summer so I don't want to volunteer right now at least. Having this feature will make it possible to support some Danish and Greenlandic legacy transformations in PROJ so at some point either @busstoptaktik or I should be able to make this a priority.

**Comment by rouault** [comment]
One downside for not including this in 6.1 is that this will affect on how we map EPSG method code 9606 and 9607 to a PROJ pipeline, and so it will change the results of proj_create_crs_to_crs() / cs2cs / projinfo -s -t etc etc. in those common situations. But there is no miracle: either we manage to slip this in 6.0, otherwise oh well... :-)

**Comment by kbevers** [comment]
> But there is no miracle: either we manage to slip this in 6.0, otherwise oh well... :-)

There's also the possibility of postponing the 6.0 release a bit. This shouldn't be the only reason, but if other things show up I am willing to consider it an option.

For now, we'll see if one of us finds the time to do it. It seems like a fun problem to solve so I'll do my best to squeeze in some time in my schedule.

**Comment by busstoptaktik** [comment]
> So you would be in favor of having a push/pop model for now ?

The push/pop model is fine to start with, and it is orthogonal to the "named register" version - both have merit, but push/pop can be implemented in the least intrusive way *and* is trivially invertible

The enormous changes of the code tree has, however, made me lose orientation, and I'm currently unproductive. It will take some time to get up to speed (I had some ideas for dramatic architectural simplification of the code base, which I'm trying to figure out whether they're still feasible).
