### ISSUE TITLE
Set proj memory allocator/deallocator

### ISSUE THREAD

**Issue by pramsey** [OSGeo/PROJ#1257]
PostgreSQL manages memory in an heirarchical context manager. In order to deal with the fact that proj allocates using malloc/free and we don't want to leak, we have a bunch of very careful machinery to clean up after proj allocations. If we could pass our memory allocator/deallocators into proj, we could remove a great deal of cruft around managing memory.

**Comment by rouault** [comment]
I assume you're speaking a PostGIS context. Can you point to what you are doing exactly ?
I'm not sure to understand why passing your own memory allocator/deallocator to PROJ would do, and if that wouldn't make PROJ unstable itself since some malloc() might be done from one code path but allocate caches that will be reused later in other contexts. So if Postgres decided to deallocate them, crash would be ensured. And that's going to be complicated with the fact that PROJ master now uses C++ new operation.

**Comment by pramsey** [comment]
Yeah, the move to C++ makes things harder, though other C++ libraries do allow this, no? External memory managers (see apache) are not so uncommon... the machinery is complex and it's in https://github.com/postgis/postgis/blob/svn-trunk/libpgcommon/lwgeom_transform.c

Basically, we cache proj PJ objects so we don't have to repeatedly look them up. So we have this long-running cache that we set up at the start of a query and don't tear down until the end. And we have no actual "query done" callback to use, so we actually end up doing crazy stuff using memory context lifetimes to simulate a "done" callback and free() the PJ item while taking down the cache structure.

So at the start of the query proj calls malloc() and hands us a PJ, and at the end we call free() on the object. If, instead, at the start of the query proj had called palloc() and given us a PJ, we could simply ignore the object and it would be freed along with all the other contents of the query context.

**Comment by rouault** [comment]
OK, so only memory allocated by proj_() calls made by PostGIS that return a PJ* object, and normally explicitly de-allocated by proj_destroy(), should be deallocated by the Postgres automatic memory collection. Not things that are cached internally. In practice that mean that only memory allocated by https://github.com/OSGeo/proj.4/blob/master/src/malloc.cpp#L198 should be automatically reclaimed, and that might be a bit more complicated than that since PJ can internally point to sub-PJ objects now, so those sub-PJ objects shouldn't be automatically destroyed since the main PJ destructor will destroy them.
And I'm not sure if it is possible to have a C++ memory allocator that is used by some objects and not by others.

**Comment by pramsey** [comment]
It's fundamentally an ownership thing... if you're passing pointers back to me and expecting me to clean them up, then it's a nice courtesy to let me get them allocated in the way I'd like. Anything you expect to free yourself you can allocate any way you like.

**Comment by kbevers** [comment]
This is mostly going over my head, but maybe I can ask a useful question: In the perfect world, how would the PROJ API expose the functionality you are asking for?

**Comment by pramsey** [comment]
The context creation step would include optional slots for callbacks with the same signatures as malloc() and free().
```
typedef void (*projfree)(void* mem);
typedef void* (*projalloc)(size_t size);
```

**Comment by kbevers** [comment]
I guess this *can* be done by adding `proj_context_set_malloc`+`proj_context_set_free` functions and by expanding `pj_malloc`, `pj_calloc`, `pj_dealloc` and `pj_dalloc` (and maybe others in `src/malloc.cpp`) to accept a pointer to a context and use whatever `malloc` and `free` function the context points to. If no context is passed, a default context should be used.

With only a few days until PROJ 6RC1 goes out the door I am not keen on working on this myself. PR's are welcome though - you have until Friday 10 AM Copenhagen time :-)

**Comment by rouault** [comment]
>  guess this _can_ be done by adding `proj_context_set_malloc`+`proj_context_set_free` functions and by expanding `pj_malloc`, `pj_calloc`, `pj_dealloc` and `pj_dalloc` (and maybe others in `src/malloc.cpp`) to accept a pointer to a context and use whatever `malloc` and `free` function the context points to.

I don't think that would work for reasons I gave above. If we allocate an internal object with the callback, then I've the feeling Postgres might then try to deallocate it automatically. But I might be wrong... If anyone wants to pursue this and experiment, it doesn't look like a change that would be sufficiently mature for 6.0.

**Comment by kbevers** [comment]
> I don't think that would work for reasons I gave above

Well, I don't see why it wouldn't work, it would just come with the ability to break things in all sorts of unfortunate ways. That's your problem if you want PROJ to use different memory management functions than it ships with. I think at least some experimentation is warranted and judging by the thumbs up on Paul's ownership comment it shouldn't be hard to find someone interested in doing said experimentation :-)
