### ISSUE TITLE
C API: add a function to tell if the axis order of a CRS is "swapped"

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1301]
@pramsey created a `proj_crs_is_swapped` function in  https://github.com/pramsey/postgis/blob/7ecf6839c57a838e2c8540001a3cd35b78a730db/liblwgeom/lwgeom_transform.c#L299 to tell if the axis order is lat/lon or northing/easting, instead of the natural GIS order, and be able to swap if needed. This might be of interest to a number of projects already using PROJ and wanting to keep the 'sane' GIS axis order rather than the EPSG one.
GDAL has also simillar code in the refreshAxisMapping() method ( https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrspatialreference.cpp#L287 ), except that it explicitly tests for "north" + "east", so as to avoid doing axis inversion for south-pole projections where the 2 axis are pointing to the north...
I'm not sure about the naming of the function however. Perhaps this should `proj_crs_axis_order_is_north_east` to be really explicit

**Comment by busstoptaktik** [comment]
I think this needs more thought.

Both axis order and direction may be anything, and not necessarily remotely resemble northerly or easterly directions or their inverses (think e.g. a crs based on oblique mercator, with central axis rotated by 30 degrees from north).

Hence `axis_order_is_north_east` is probably not a sufficiently instructive predicate. I think this API section may need two entries: One for "normalizing for visualization", and one telling whats being done.

Alternatively, we could provide a single API entry returning a proper argument for an axisswap pipeline entry... in loosely defined pseudocode, reflecting an actual use case I’m involved with currently:

    crs = “proj=omerc axis=nwu ellps=GRS80 gamma=0.0 lonc=A lat_0=B x_0=C y_0=D k=E alpha=F”; // A-F are arbitrary constants
    P = proj_create (crs);
    swaporder = proj_normalize_for_visualization (P); // returns “-2,1,3,4”
    proj_destroy (P);
    P = proj_create (“proj=pipeline step ”  + crs +  “step proj=axisswap order=” + swaporder);

`proj_crs_axis_order_is_north_east` is probably better than `proj_crs_is_swapped`, since it does not imply the existence of a canonical axis order that a crs can be swapped in relation to. Even better would be `proj_crs_axis_order_is_NOT_east_north`, but all of them is, IMHO, a waste of API surface since, really, a more general interface is probably needed.

**Comment by rouault** [comment]
> Both axis order and direction may be anything, and not necessarily remotely resemble northerly or easterly directions or their inverses (think e.g. a crs based on oblique mercator, with central axis rotated by 30 degrees from north).

Yes, but let's look at the EPSG:6808 definition : https://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::6808  . It advertizes east, north direction despite `Azimuth of initial line`  = `Angle from Rectified to Skew Grid`  = 295 , so it seems the meaning of east & north is quite loose. ISO-19111 (even the 2007 revision) and WKT-2 (even the 2015 revision) can express other more fine grained directions such as northnortheast, etc. (http://docs.opengeospatial.org/is/12-063r5/12-063r5.html#36). I'm not sure why they aren't used in EPSG coordinate system definitions. Perhaps for compatibility with WKT1 which only allows for the 4 cardinal directions.

> Hence `axis_order_is_north_east` is probably not a sufficiently instructive predicate

This is clearly a particular case, but I believe this is the one that will be hit in 90% of the 'odd' axis order situations, and for which we have a clear normalization path (switch axis). That said if we have the normalization API (with the admentment I suggest below), it might be unneeded. `proj_crs_axis_order_is_NOT_east_north` is less interesting since for Polar projections this is the case, but you generally don't need to do normalization

> One for "normalizing for visualization"

In fact the use case is more that you get a pipeline with `proj_create_crs_to_crs(ctxt, "EPSG:XXXX", "EPSG:YYYY")` that would potentially need to be normalized at both ends. At least that's the PostGIS use case. So `proj_normalize_for_vizualisation` could return a corrected PJ* object rather than a string.

**Comment by kbevers** [comment]
> In fact the use case is more that you get a pipeline with proj_create_crs_to_crs(ctxt, "EPSG:XXXX", "EPSG:YYYY") that would potentially need to be normalized at both ends. At least that's the PostGIS use case. So proj_normalize_for_vizualisation could return a corrected PJ* object rather than a string.

I think this is the best way to proceed from the options listed above. With the aim being that the function provides a `PJ` object that mostly behaves as PROJ did before version 6. Disclaimers about this not being the intended use of the CRS should be added to the documentation and probably also an example or two of best practice in common situations.
