### ISSUE TITLE
proj 6.0.0 apps/proj.cpp uses pj_get_datums_ref()

### ISSUE THREAD

**Issue by rsbivand** [OSGeo/PROJ#1306]
proj 6.0.0 apps/proj.cpp uses pj_get_datums_ref(), but the structure and function is exposed in proj_internal.h, which is not installed. So code in R `rgdal::projInfo("datum")` cannot list datums as in < 6 (even when copying the declarations locally because of obfuscation in C++ I think). I'm assuming that this was an intended shift to defunct, but cannot find documentation. @edzer: this also affects `sf::st_proj_info("datum")`. Not a big problem as the functions are only used for information, but I'd like to link my warning to users in the function to where the decision is documented. The other varieties in `c("proj", "ellps", "datum", "units")`) still work as `proj_list_operations()`, `proj_list_ellps()` and `proj_list_units()` are in proj.h.

**Comment by kbevers** [comment]
Yeah, it's not exposed on purpose. The list of datums you get from that function is incomplete and using the `+datum` option should be avoided in the future. The other `proj_list_*` functions are more usable which is why they've been carried over from the old API.

I think we should remove the `proj -ld` functionality in PROJ 7. We have better ways to achieve that today.

**Comment by kbevers** [comment]
What do you propose be done to resolve this issue? Add a section on https://proj4.org/usage/differences.html ? I see that we haven't included that `projects.h` is removed from PROJ 6, which I guess in principle covers this issue. It is mentioned in the release notes though, so that can also be referred to.

**Comment by rsbivand** [comment]
It is in the release notes, so covered there. I'll document the change as you suggest, that "the list of datums is incomplete, and using the +datum option should be avoided in the future".
