### ISSUE TITLE
jniwrap fails to build with Java 8

### ISSUE THREAD

**Issue by kalxas** [OSGeo/PROJ#1320]
The jniwrap bindings fail to build with OpenJDK 8:

```
compile:
    [mkdir] Created dir: /<<PKGBUILDDIR>>/jniwrap/out
    [mkdir] Created dir: /<<PKGBUILDDIR>>/jniwrap/out/classes
    [javac] Compiling 4 source files to /<<PKGBUILDDIR>>/jniwrap/out/classes
    [javac] javac: invalid flag: --module-version
    [javac] Usage: javac <options> <source files>
    [javac] use -help for a list of possible options

BUILD FAILED
/<<PKGBUILDDIR>>/jniwrap/build.xml:23: Compile failed; see the compiler error output for details.
```
I see in #974 that this module has moved forward.
Is there any supported way to use OpenJDK 8?

**Comment by rouault** [comment]
CC @desruisseaux 
I see Debian dropped the libproj-java package for PROJ 6 : https://salsa.debian.org/debian-gis-team/proj/commit/279b1c6f1f2d01eb105be2b49a5c7fa5e919ef4f
On Travis-CI, we have very minimal compile testing against OpenJDK 7

**Comment by desruisseaux** [comment]
Indeed the requirement for JNI bindings moved to Java 9 in order to benefit from modularisation ("Jigsaw"). But it is possible to support also older Java versions using "multi-versions JAR file" or other approach. I have not done that because I didn't knew if there would be a demand. If this is the case I can do it.

One question however: is it okay to require Java 9+ at _build_ time (but allow the compilation result to run on older Java versions), or is it required to build the project with older Java versions too? I ask because "multi-versions JAR files" is available only with Java 9+ compilers.

**Comment by rouault** [comment]
> Indeed the requirement for JNI bindings moved to Java 9 in order to benefit from modularisation ("Jigsaw")

OK, actually I realize that Travis with OpenJDK 7 only tests the compilation of the native part of the Java bindings (and native JNI stuff must not be that much dependent of the Java version), but not the Java code itself.
Not sure if someone actually tested that the PROJ 6 Java binding works at runtime after all the work of the past months.

I don't have a strong opinion about which Java version we should support, but it would be interesting to have @sebastic feedback why he had to disable libproj-java: I would have assumed that Debian unstable/testing used a recent Java version.

**Comment by sebastic** [comment]
The JNI bindings failed to build with OpenJDK 11 in Debian unstable. I don't have the buildlog for the details any more.

Since the libproj-java package isn't used by any other packages, and because it unblocks other packages on a couple of ports (see [837354](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837354)), it was enough for me to decide to drop the package now.

**Comment by desruisseaux** [comment]
The C/C++ side of JNI is very stable. As far as I know, the `src/org_proj4_PJ.h` file generated by Java 9 is practically identical to the file generated 15 years ago by Java 5. It is possible to compile the C code while ignoring the Java classes, if desired, and let Java developers compile the Java classes themselves for now.

On short term we can fix the build (I would have to check with Java 11 on my side) after a choice has been made about which minimal Java version to require. I'm neutral about whether it should be for this PROJ version or a next one. On medium term revisit the Java bindings in light of the new API available in PROJ, but I guess it would be the topic of another github ticket.

**Comment by kbevers** [comment]
Since #1825 jni wrappers has been removed from PROJ. This issue no longer applies.
