### ISSUE TITLE
Unable to build PROJ binaries

### ISSUE THREAD

**Issue by anthonygardner** [OSGeo/PROJ#1518]
Hi, I have not been able to build PROJ's binary dependencies using cmake:

![proj_error](https://user-images.githubusercontent.com/35740203/59630701-9d39f600-910b-11e9-8c80-a0d797eac165.PNG)

**Comment by QuLogic** [comment]
> Configuring incomplete, errors occurred!

Did you read the errors? You haven't posted them.

**Comment by anthonygardner** [comment]
[CMakeError.log](https://github.com/OSGeo/PROJ/files/3298849/CMakeError.log)
[CMakeOutput.log](https://github.com/OSGeo/PROJ/files/3298850/CMakeOutput.log)

**Comment by kbevers** [comment]
This is most likely not a problem with PROJ, but failure to understand how to properly use CMake to build the software. I am closing this issue since there's in not sufficent information to advise on how to solve the problem. 

There's plenty of good resources on building PROJ on Windows. Follow either [this howto](https://github.com/OSGeo/PROJ/wiki/Building-with-VS-and-vcpkg), [this guide in the docs](https://proj.org/install.html#cmake) or find inspiration in [the continous integration setup](https://github.com/OSGeo/PROJ/blob/master/appveyor.yml).
