### ISSUE TITLE
configure: SQLITE3_CFLAGS  and SQLITE3_LIBS to avoid the need to call pkg-config

### ISSUE THREAD

**Issue by multiquadric** [OSGeo/PROJ#1529]
proj 6.1.0
macOS 10.14.4
Probably applies to Linux, etc.

 $ ./configure -prefix=/opt/proj-6.1.0 SQLITE3_CFLAGS=-I/opt/sqlite-3.28.0/include SQLITE3_LIBS=-L/opt/sqlite-3.28.0/lib -lsqlite3 CC=gcc -arch x86_64 CXX=g++ -arch x86_64 CPP=gcc -E CXXCPP=g++ -E CPPFLAGS=-I/opt/sqlite-3.28.0/include LDFLAGS=-L/opt/sqlite-3.28.0/lib -lsqlite3

The checks for  SQLITE3_CFLAGS  and SQLITE3_LIBS may be incorrect. The last check may be tweaked for success as follows (basically reordering else and elif content

).
$ diff configure configure.ORIGINAL
18924,18929d18923
<     SQLITE3_CFLAGS=$pkg_cv_SQLITE3_CFLAGS
<     SQLITE3_LIBS=$pkg_cv_SQLITE3_LIBS
<         { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
< $as_echo "yes" >&6; }
<     :
< else
18941a18936,18941
> else
>     SQLITE3_CFLAGS=$pkg_cv_SQLITE3_CFLAGS
>     SQLITE3_LIBS=$pkg_cv_SQLITE3_LIBS
>         { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
> $as_echo "yes" >&6; }
>     :
$

**Comment by kbevers** [comment]
@multiquadric Please open a pull request with this change. It seems like a good thing to change but I would like to see how this does on the continous integration tests. Also, you get credit for your patch :)

**Comment by rouault** [comment]
If a change must be done, then it is in configure.ac, not configure. The later is generated from the former. But I doubt that any change is needed at all...
This might be an issue with missing double quotes in your ./configure invokation. I would do SQLITE3_LIBS="-L/opt/sqlite-3.28.0/lib -lsqlite3", etc.

**Comment by kbevers** [comment]
Good point. @multiquadric, please try adding quotes and see if that works for you.

**Comment by multiquadric** [comment]
Apologies. A copy & paste from the config.log file does not work very well. I knew that. The quotation marks were stripped from the command-line. Here is the command from the Bash shell history:

  466  ./configure -prefix=/opt/proj-6.1.0 SQLITE3_CFLAGS=-I/opt/sqlite-3.28.0/include SQLITE3_LIBS="-L/opt/sqlite-3.28.0/lib -lsqlite3" CC="gcc -arch x86_64" CXX="g++ -arch x86_64" CPP="gcc -E" CXXCPP="g++ -E" CPPFLAGS=-I/opt/sqlite-3.28.0/include LDFLAGS="-L/opt/sqlite-3.28.0/lib -lsqlite3"

The checks came back OK too.

  481  make check

I'll have  a read on configure.ac and to try to help with the template changes, if needed. Might not happen right away.

Thanks

**Comment by kbevers** [comment]
@multiquadric 	Make use of the formatting tools to avoid such problems. Place your pasted text wrapped in triple-ticks like this:

````
```
pasted stuf goes here
```
````

**Comment by kbevers** [comment]
@multiquadric Any update on this?

**Comment by multiquadric** [comment]
Regrets. No free time. I did use the changes ( to "configure" ) in proj 6.1.0 with 6.1.1 and achieved good results :-)  Need to learn about the whole template business ....

**Comment by forestgnome** [comment]
proj 6.1.1
macOS 10.14.5
I ecnountered the same problems like multiquadric. From my view, the whole PKG_CONFIG-check is the problem.
I removed the whole PKG_CONFIG-stuff within configure (which is not defined  in configure.ac !?)
Now I used
		configure \
			SQLITE3_CFLAGS="-I$sqliteDir/include" \
			SQLITE3_LIBS="-L$sqliteDir/lib -lsqlite3" \
			--prefix=$projInstallDir
and the whole proj compiles and links fine.

**Comment by jakob** [comment]
I think I have the same issue.

I've tried building PROJ 6.2 on macOS, and `./configure` always failed, complaining about a missing / too old version of pkg_config. It seems that the configure script uses pkg_config to check if a recent enough version of SQLite3 is available, and to get the compiler/linker flags for SQLite3.

The error message from the configure script suggests that setting `$SQLITE3_CFLAGS` and `$SQLITE3_LIBS` to avoid the need to call pkg_config, but unfortunately that doesn't help. pkg_config is called and fails whether the variables are set or not.

As far as I understand, if the user provides `$SQLITE3_CFLAGS` or `$SQLITE3_LIBS`, the call to pkg_config should not be necessary. So I suggest a change to `configure.ac`, which first tests if these variables are set, and only calls pkg_config if they are not set.

I am going to submit a pull request with that change (update: submitted PR #1651).

But of course that only fixes part of the issue -- the user must still know to set the environment variables before calling configure. But the point of the configure script should be to detect the build settings automatically. For example, on macOS, passing `-lsqlite3` is enough, since SQLite3 ships with macOS, and the headers are in the default search path. The dependency on pkg_config is unnecessary, and it would be better if the configure script just tried using `SQLITE3_LIBS=-lsqlite3` before even calling pkg_config.

I'm not sure how one would have to change the `configure.ac` script to accomplish that, so I hope someone more experienced would help with that.

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/PROJ/pull/1651

**Comment by akontsevich** [comment]
> Now I used
> configure
> SQLITE3_CFLAGS="-I$sqliteDir/include"
> SQLITE3_LIBS="-L$sqliteDir/lib -lsqlite3"
> --prefix=$projInstallDir
> and the whole proj compiles and links fine.

For me it does not. I do the following in docker building for android:
```
FROM android as proj

ENV BUILD_DIR=/proj/build
ENV INSTALL_DIR=/proj/${ABI}
ENV SQLITE3_CFLAGS="-I${SQLITE_INSTALL_DIR}/include"
ENV SQLITE3_LIBS="-L${SQLITE_INSTALL_DIR}/lib -lsqlite3"

RUN mkdir -p "${BUILD_DIR}" && \
    mkdir "${INSTALL_DIR}"
WORKDIR "${BUILD_DIR}"

RUN git clone https://github.com/OSGeo/PROJ.git && \
    cd PROJ && \
    git checkout "${PROJ_VERSION}"

RUN cd PROJ && \
    ./autogen.sh && \
    ./configure --host="${HOST}" --prefix="${INSTALL_DIR}" && \
    make clean && \
    make -j $(nproc) && \
    cd src && \
    make install
```
and it builds fine however link fails for some reason. I'm using 6.3.2 version. Have I missed something?!
