### ISSUE TITLE
Area of use for operation inconsistencies

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/PROJ#1549]
I'm seeing some strange results in the area of use for coordinate operations. One example is:

./projinfo EPSG:3111

```
WKT2_2018 string:
...
    USAGE[
        SCOPE["unknown"],
        AREA["Australia - Victoria"],
        BBOX[-39.2,140.96,-33.98,150.04]],
    ID["EPSG",3111]]
```

./projinfo EPSG:7844

```
WKT2_2018 string:
...
    USAGE[
        SCOPE["unknown"],
        AREA["Australia - GDA"],
        BBOX[-60.56,93.41,-8.47,173.35]],
    ID["EPSG",7844]]
```

./projinfo -s EPSG:3111 -t EPSG:7844

```
Operation n°1:
...
PROJ string:
+proj=pipeline +step +inv +proj=lcc +lat_0=-37 +lon_0=145 +lat_1=-36 +lat_2=-38 +x_0=2500000 +y_0=2500000 +ellps=GRS80 +step +proj=push +v_3 +step +proj=cart +ellps=GRS80 +step +proj=helmert +x=0.06155 +y=-0.01087 +z=-0.04019 +rx=-0.0394924 +ry=-0.0327221 +rz=-0.0328979 +s=-0.009994 +convention=coordinate_frame +step +inv +proj=cart +ellps=GRS80 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1

WKT2_2018 string:
...
    USAGE[
        SCOPE["unknown"],
        AREA["Australia - GDA"],
        BBOX[-60.56,93.41,-8.47,173.35]]]
```

**Shouldn't this be the intersection of the two bboxes, instead of the bbox from EPSG:7844 alone?** Definitely EPSG:3111 shouldn't be used outside of Australia - Victoria, so a coordinate operation giving an area of use of the whole of Australia is misleading.

I see similar results when calculating operations between any of the MGA zones (e.g. EPSG28356 to EPSG7844), or EPSG:7856 to EPSG:3111.

**Comment by rouault** [comment]
Tricky topic. I'm not sure to remember all the implications, but there were issues in being too restrictive. When you consider the area of use of a projected CRS, this is mostly a soft indication, because most map projection methods are exact mathematically speaking on a much larger area than their intended area of use. You can for example decide in a country that has several UTM zones to use the central one because this is more convenient, and that will be fine and perfectly well defined mathematically. Where the area of use of a Helmert transformation is derived from experimental results that have really a defined area of validity (and for a grid based transformation this is obvious that the area of use must be considered in a restrictive way). So in a concatenated operation, the area of use of the CONVERSION steps is ignored. Only the area of use of the COORDINATEOPERATION steps is taken into account in the intersection : https://github.com/OSGeo/PROJ/blob/master/src/iso19111/coordinateoperation.cpp#L426

**Comment by nyalldawson** [comment]
Ok - so (to paraphrase) - the crs area of use is based on the database metadata alone, while the operation area of use is based on the mathematical properties of the operation. Is my understanding correct?

If so, and I'm just after an area of use to show users as a "this operation is valid for use in this bbox" widget (i.e. a visual indicator only), I guess I could take the area of intersection from the source, destination AND operation bboxes combined?

**Comment by rouault** [comment]
> the crs area of use is based on the database metadata alone, 

yes

> while the operation area of use is based on the mathematical properties of the operation. Is my understanding correct?

yes. Or at least my own interpretation of what we should do in that situation :-)

> If so, and I'm just after an area of use to show users as a "this operation is valid for use in this bbox" widget (i.e. a visual indicator only), I guess I could take the area of intersection from the source, destination AND operation bboxes combined?

Up to you. There are pros and cons in both approaches of being too restrictive or too lax.

**Comment by nyalldawson** [comment]
Ok, thanks!
