### ISSUE TITLE
Transform Z coordinate doesn't works on a lot of canonical Coordinate System 

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/PROJ#1587]
Transform Z coordinate  doesn't works on a lot of canonical Coordinate System  in 

## Steps to reproduce the problem.

transform coordinate  Z doesn't works, for example, on the following CS's:

**sources CS samples:**
The first one is 3D. I am not sure if the second and the third is also 3D.
if not, how can I make them 3D ?

1. 

PROJCS["ENU (-77.410692720411:39.4145340892321)",GEOGCS["WGS 84",DATUM["World Geodetic System 1984",SPHEROID["WGS 84",6378137.0,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0.0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.017453292519943295],AXIS["Geodetic latitude",NORTH],AXIS["Geodetic longitude",EAST],AXIS["Ellipsoidal height",UP],AUTHORITY["EPSG","4979"]],PROJECTION["Orthographic"],PARAMETER["Latitude_Of_Center",39.4145340892321],PARAMETER["Longitude_Of_Center",-77.410692720411],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]]

2. 
PROJCS["OSGB 1936 / British National Grid",GEOGCS["OSGB 1936",DATUM["OSGB_1936",SPHEROID["Airy 1830",6377563.396,299.3249646,AUTHORITY["EPSG","7001"]],AUTHORITY["EPSG","6277"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4277"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",49],PARAMETER["central_meridian",-2],PARAMETER["scale_factor",0.9996012717],PARAMETER["false_easting",400000],PARAMETER["false_northing",-100000],AUTHORITY["EPSG","27700"],AXIS["Easting",EAST],AXIS["Northing",NORTH]]

3.
PROJCS["Orthographic (-85.4876596902845000,32.6035190542778000)",GEOGCS["GCS_WGS_1984",DATUM["D_unknown",SPHEROID["WGS84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Orthographic"],PARAMETER["Latitude_Of_Center",32.6035190542778000],PARAMETER["Longitude_Of_Center",-85.4876596902845000],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]]

**Destination CS:**

COMPD_CS["WGS 84 + EGM96 geoid height",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AXIS["Latitude",NORTH],
        AXIS["Longitude",EAST],
        AUTHORITY["EPSG","4326"]],
    VERT_CS["EGM96 height",
        VERT_DATUM["EGM96 geoid",2005,
            AUTHORITY["EPSG","5171"]],
        UNIT["metre",1,
            AUTHORITY["EPSG","9001"]],
        AXIS["Gravity-related height",UP],
        AUTHORITY["EPSG","5773"]]] 

## Operating system

Windows 10

**Comment by kbevers** [comment]
You haven't actually explained how to reproduce your problem. A bunch of CRS descriptions is not enough. What command are you running? What is your input data? What is wrong with the output?

**Comment by rouault** [comment]
Original GDAL ticket with a few more comments is in https://github.com/OSGeo/gdal/issues/1818

@kbevers This is a bit of a grey area. I think that if we transform between two 2D CRS, we don't want height transformation to occur, right ?. But when transforming between a 2D and a 3D CRS (3D being either geographic 3D CRS, compound CRS, or more rarely a projected 3D CRS), currently we don't do the vertical transformation. What is annoying in practice for users is that if the 2D CRS they have is a Projected CRS, it is not obvious at all to make it a Projected 3D CRS which is a rather esoteric object even for specialists. So I'd be tempted to relax things to allow for Z transform if at least one of the CRS is 3D, even if that's probably not ISO-19111 cosher. Thoughts ? Actually, thinking more, allowing this is kind of opening a can of worms, because we'd have to define how the vertical axis is defined for the 2D CRS promoted to 3D: if it is a Projected 2D CRS, that would be the corresponding Projected 3D CRS where its base geographic 2D CRS is promoted to a geographic 3D CRS with the Z axis up and in meters, and similarly for a Geographic 2D CRS to be promoted to a Geographic 3D CRS.
Or perhaps have some easy way in the API & utilities to derive a 3D CRS from a 2D one ? That way there wouldn't be any (new...) implicit magic happening.

**Comment by aharondavid** [comment]
currently, we do have a serious problem:
we have a lot of projects that has coordinate system transformed by GDAL 
and now (GDAL 3) they broken.
we will be glad if there is a way to derive a 3D CRS from a 2D or a way to preserved the old behavior

**Comment by aharondavid** [comment]
Excellent! , @rouault , Thank you so much. 
According to your change, can you insert the change also in GDAL ?
I thought on method like:
OGRSpatialReference::PromoteTo3D()

**Comment by aharondavid** [comment]
Done:
[New ticket added.](https://github.com/OSGeo/gdal/issues/1852)

Thanks!
