### ISSUE TITLE
Antimeridian Cutting

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1657]
Related to: 
- https://github.com/geopandas/geopandas/issues/448
- https://github.com/OSGeo/gdal/commit/cc92ccb7a01321efed8cfc820fc7215aba12b1f1

What is the current recommended method for antimeridan cutting with PROJ? In the geopandas issue above it mentions `+over`, but much has changed. 

ping @jorisvandenbossche

**Comment by rouault** [comment]
Your question is more how to deal with geometries if I understand well, than with single point re-projection which is PROJ core business. I recognize this is a complex issue and have myself dealt with that issue in GDAL as you pointed about, but I'm not sure what PROJ can do about that. One thing that could help is is somehow PROJ could return for a given reprojection from A to B the geometry expressed in A coordinates that will be the frontier of discontinuity. For example if A is polar stereographic and B longlat, then this geometry is a semi-infinite line with one extremity at the pole and then running along the 180/-180 meridian, etc. But in practice so that the geometry cutting works well when your geometries are polygons, you rather need to use as an intersection mask a "infinite" polygon with a kind of "needle" making a small circle around the pole (I'm pretty sure you can't make sense of that sentence. I should do a drawing...), which is what I implemented in GDAL (https://github.com/OSGeo/gdal/commit/cc92ccb7a01321efed8cfc820fc7215aba12b1f1#diff-3bd12ba4f85a48b0e3f9e5c28e5a746cR3003). I don't think there's an automated way for PROJ to do that. It is strongly tied to each (A, B) CRS pair, and knowing the characteristics of the projections. A herculean task !

**Comment by snowman2** [comment]
Indeed, a complex issue. I wonder if adding a kwarg to transform_from_crs_to_crs or proj_trans/proj_trans_generic that allows the user to toggle one of these options would be a simpler method to proceed? https://proj.org/usage/projections.html#longitude-wrapping

**Comment by snowman2** [comment]
Hmmm, maybe not. The geometry itself would need to be cut as the points would be transformed correctly.

**Comment by snowman2** [comment]
Thanks for your input @rouault!

**Comment by jorisvandenbossche** [comment]
Indeed, the linked discussion focusses around projection of a set of coordinates together (a geometry), instead of projecting the coordinates independently.

> I don't think there's an automated way for PROJ to do that. It is strongly tied to each (A, B) CRS pair, and knowing the characteristics of the projections. A herculean task !

In what way is the method that you implemented in GDAL then not herculean? It only does it for a small subset of possible projections supported in PROJ?

I fully understand that this is a complex issue and not necessarily in scope for PROJ. But when @snowman2 mentioned the geometry transform method in GDAL / fiona, my first reaction was if this could not fit in PROJ instead of having it in GDAL.

There seem to be several libraries that are using PROJ and extend it to deal with those issues (eg also cartopy does that).

**Comment by rouault** [comment]
> In what way is the method that you implemented in GDAL then not herculean? It only does it for a small subset of possible projections supported in PROJ?

Yes, for just 2 cases if I remember well.

> There seem to be several libraries that are using PROJ and extend it to deal with those issues

Agreed, just that dealing with linear or polygonal geometry is not in the scope of PROJ, at least currently. This is completely in the scope of GDAL (I assume from the above remark that cartopy doesn't use fiona and GDAL ?)

**Comment by jorisvandenbossche** [comment]
> (I assume from the above remark that cartopy doesn't use fiona and GDAL ?)

Yes, they combine PROJ and GEOS and have some custom logic to project lines (https://github.com/SciTools/cartopy/blob/master/lib/cartopy/trace.pyx), and then some more higher level logic for the different types of geometries based on this.
