### ISSUE TITLE
Convert Irish Coordinates to GPS coordinates for google maps

### ISSUE THREAD

**Issue by fabiom91** [OSGeo/PROJ#1687]
Let's pretend I know nothing about coordinates, geography etc.
I have a dataset which has 2 features: Irish_X and Irish_Y. I need to convert those kind of coordinates in a readable ones for Google maps:

<img width="469" alt="Screenshot 2019-10-21 at 09 23 54" src="https://user-images.githubusercontent.com/42029814/67188574-83276180-f3e4-11e9-9d42-e1fe3ee18b6a.png">

Can I do it with PROJ? and how?
Thank you!

**Comment by fabiom91** [comment]
I found this on stack exchange but I think is doing the opposite conversion:
[https://gis.stackexchange.com/questions/32418/python-script-to-convert-lat-long-to-itm-irish-transverse-mercator](url)

```python
from pyproj import Proj, transform


def reproject_wgs_to_itm(longitude, latitude):
    prj_wgs = Proj(init='epsg:4326')
    prj_itm = Proj(init='epsg:2157')
    x, y = transform(prj_wgs, prj_itm, longitude, latitude)
    return x, y


print reproject_wgs_to_itm(-7.748108, 53.431628)
```

**Comment by kbevers** [comment]
> Let's pretend I know nothing about coordinates, geography etc.
I have a dataset which has 2 features: Irish_X and Irish_Y.

> Can I do it with PROJ? and how?

No. You need to know what coordinate reference system your input coordinates are related to for PROJ to make any sense of it. If your data is in fact ITM (EPSG:2157) then PROJ can help you:

```
echo 313938.823343 234607.147947 | cs2cs -d 4 EPSG:2157 EPSG:4326
48.8006 -11.8950 0.0000
```

which gives you a WGS84 representation of the first coordinate in your list.

As for you code example, it seems to be correct but the reverse way round as you say. Switch the input and output CRS to get the transformation right. But, since your code is using pyproj you should seek help for that at the pyproj project and not here. See https://github.com/pyproj4/pyproj

**Comment by fabiom91** [comment]
Thank you kbevers, I actually tried to embed the bash command you posted into my python code with not good results (my Jupiter notebook is behaving weird). then I solved finding a new dataset.
