### ISSUE TITLE
Including Python scripts related to GeoTIFF grids ?

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1850]
Per RFC-4, a number of python scripts to create GeoTIFF grids from existing .gsb/.gtx, optimizing existing GeoTIFF files or checking compliance of GeoTIFF files regarding RFC-4 have been developed in https://github.com/rouault/sample_proj_gtiff_grids/ .
They should likely be hosted in a more official and visible location. I guess PROJ would be the most appropriate candidate to host them (although most of those scripts require GDAL & the GDAL Python bindings to be available)
An idea would be to put them in a utils/ directory. Should they be installed in ${prefix}/bin as well as part of "make install" ? If so, we might want to namespace them with a proj_ prefix
I'd also need to add some documentation for them in the main doc. Probably as a standalone page pointed by https://proj.org/resource_files.html ?
I also think that the PROJ GeoTIFF specification should be extracted from RFC-4 to be put in a dedicated page that can be directly refered to (to make its adoption easier)

**Comment by kbevers** [comment]
> As they already have Doxygen doc, this is addressed by c40ee9d that just uses Breathe to include it in the appropriate sections

Definitely!

> An idea would be to put them in a utils/ directory. Should they be installed in ${prefix}/bin as well as part of "make install" ? If so, we might want to namespace them with a proj_ prefix

Installing them via `make install` would introduce dependencies to Python and GDAL. That's probably not a good idea. We could of course just offer them as part of the source tarball and let users deal with the Python environment. Another option is to include them in the proj-datumgrid* repository. In a way I think that makes the most sense, since whoever will be using the scripts will likely also want to submit their grids for inclusion in our grid package(s).

> I'd also need to add some documentation for them in the main doc. Probably as a standalone page pointed by https://proj.org/resource_files.html ?

Yeah, somewhere under the "resource files" chapter. Maybe a good opportunity to split that up into separate files.

> I also think that the PROJ GeoTIFF specification should be extracted from RFC-4 to be put in a dedicated page that can be directly refered to (to make its adoption easier)

Absolutely. This needs to be advertised! We now maintain two specifications: PROJJSON and PROJ GeoTIFF. Perhaps that is enough for a top-level section on the website? "Specifications" or whatever. Could also be expanded to include info on various types of WKT and the database layout of `proj.db` (not sure if that is a good idea...).

**Comment by rouault** [comment]
> Another option is to include them in the proj-datumgrid* repository

Which one: proj-datumgrid or proj-datumgrid-geotiff ? (I don't think we have reached to a conclusion to my email thread regarding possibly adopting proj-datumgrid-geotiff. I can feel a lack of enthusiasm. Probably expected. Normal resistance to change :-))
If we don't adopt proj-datumgrid-geotiff (yet...), perhaps in proj-datumgrid itself, so that people have the possibility to contribute GeoTIFF grids in it. Or we could also jump to: any new grid would be a GeoTIFF one, so that we have a smooth transition ?

> PROJ GeoTIFF

I would probably not put "PROJ" in the name, so that we encourage wider adoption by other implementations. "Geodetic adjustment GeoTIFF grids" (GAGG) maybe, or "GeoTIF Geodetic adjustment grids"  (GGAG)

> and the database layout of proj.db (not sure if that is a good idea...).

Not sure either. Mostly an implementation detail, and something likely to evolve over time.

**Comment by kbevers** [comment]
> Which one: proj-datumgrid or proj-datumgrid-geotiff ? (I don't think we have reached to a conclusion to my email thread regarding possibly adopting proj-datumgrid-geotiff. I can feel a lack of enthusiasm. Probably expected. Normal resistance to change :-))

Well... that's why I put the * in there. I don't know. I had hoped a clear consensus would come from you bringing up the topic on the list but that didn't really take off. I'm happy to go full -geotiff. As far as I can tell it makes life simpler for me and that is what matters most for me at this point. We should make a decision on this soon. Perhaps put it up for a PSC vote, as a couple of yes/no questions: "Do you wan't -geotiff to be the main grid repository?" and "Ditch the regional packages in favour for a all-inclusive grid package?". Or something to that effect.

> I would probably not put "PROJ" in the name, so that we encourage wider adoption by other implementations. "Geodetic adjustment GeoTIFF grids" (GAGG) maybe, or "GeoTIF Geodetic adjustment grids" (GGAG)

Sure. I'm just going with what I've seen so far. I prefer acronyms that can be easily pronounced :)

**Comment by ccrook** [comment]
On the original question would it make sense to create a package proj-util or the like such utilities?

> I would probably not put "PROJ" in the name, so that we encourage wider adoption by other implementations. "Geodetic adjustment GeoTIFF grids" (GAGG) maybe, or "GeoTIF Geodetic adjustment grids" (GGAG)

My vote is not to include "adjustment" - sounds like least squares adjustment of geodetic observations.  I'd rather see a T in there to identify the TIFF part.  Definitely agree on using something generic and not PROJ specific.  GTG (Geodetic TIFF grids) or some variant?

> "Ditch the regional packages in favour for an all-inclusive grid package?".

Is this the right way to go?  This works now but I think grids are likely to grow rapidly, especially as agencies will be increasingly dealing with deformation (ever more demanding accuracy specs) and observations techniques such as INSAR could lead to more frequent and more detailed grids being generated.  I guess the intention is that the CDN will replace packaged grids, but for disconnected use cases I'd have thought moving the other way to source agency specific datasets makes more sense?  I think in a previous discussion there was concern about the packaging overhead of each grid package ... maybe that is also a reason not to create proj-util :-(

**Comment by rouault** [comment]
> a package proj-util or the like such utilities?

A dedicated GitHun repository you mean ? IMHO that's going to be a bit hard to manage and people will be lost between repositories.

> GTG (Geodetic TIFF grids) or some variant?

GTG would be fine to me (GAGG has the advantaged to have a vowel). There's no such GDAL driver name yet :-)

**Comment by rouault** [comment]
Brainstorming a bit...

Regarding packaging of grids, what is if the PROJ project would only release a single proj-datumgrid-geotiff-XXX.zip, which would reflect the organization in subdirectories of https://github.com/OSGeo/proj-datumgrid-geotiff instead of putting them in a flat way ? That way Linux/BSD/Windows packagers could take it as it, or it if they prefer create multiple packages organized by agency (or group of agencies for a regional strategy) with the content of the subdirectories.

One consequence of this though is that you wouldn't call +grids=ntf_r93.tif but +grids=fr_ign/ntf_r93.tif , and that would require code changes so to map automatically ntf_r93.gsb to fr_ign/ntf_r93.tif (we'd probably need the help of the database to figure out to which agency a file belongs to)

Or maybe simpler, keep the flat structure of the monolithic archive, but have a {agency}_filelist.txt with the list of files related to each agency. That should likely be good enough material for packagers wanting to split the monolithic archive into smaller ones to automate such creation with minimal maintenance effort

**Comment by ccrook** [comment]
> A dedicated GitHun repository you mean ? IMHO that's going to be a bit hard to manage and people will be lost between repositories.

I think you are right -  a dedicated repo probably doesn't make sense.  But maybe it could be a separate package built from the repo so that it has the necessary dependencies for the utilities.  However I'm no packaging expert (understatement!) so perhaps this is not practical in packaging for multiple target platforms.

**Comment by ccrook** [comment]
> Brainstorming ...

Some sort of grid namespace would be good - particularly as some of the existing grids have very ambiguous names.  There is already grid_alternatives to handle some renaming - possibly that could be automatically populated with mapping to agency directories.  Or if there was a way of populating grid_alternatives from the proj-datumgrid-xxx rather than in proj itself that could be cleaner.

**Comment by rouault** [comment]
Related to RFC5: https://github.com/OSGeo/PROJ/pull/1868
