### ISSUE TITLE
Rethink error handling

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#1856]
Over in #1855, @rouault says:

> Error handling in PROJ looks really super fragile & hard to comprehend to me. The concept of persistent vs transient errors, when the error state is supposed to be reset or not.. Not sure I've a good idea how to make it simpler...

a.o. mentioning that:

> I've also modified pipeline.cpp so that when a step returns HUGE_VAL for .x, we early exit instead of running the next step that would reset the error state due to int last_errno = proj_errno_reset(P) being used in fwd.cpp & inv.cpp, for a unclear reason to me...

Error handling in "classic" proj was seriously odd, and working around its (presumed) assumptions while designing the 4D API did not make it less obscure. Pre-4D-API code apparently worked on the (mostly wrong) assumption that `errno` isn't thread-local (it is), an hence mixing the error handling between the (actually thread-local) errno and its copy in the `PJ_CONTEXT`.

Basically, I decided to (try to) preserve existing behaviour as far as possible, although I was quite convinced that existing behaviour was wrong. But you cannot rebuild the entire world at once - you need some foundation to build on.

Changing the error handling and error messaging would be a major architectural undertaking, without any clear improvements feature wise, so it is hard to argue for funding of. I do however, believe that such work can seriously improve the code base.

In the C world, practice should have been to refuse to work as long as errno is nonzero, checking after (almost) each internal function call, and just bubble up to the application level (releasing allocated ressources on the way up), where it can be handled.

But now, we're in a C++ world and can do C++ error handling, although I personally don't like the thought of library code throwing exceptions at me. I think the golang practice of returning a `(result, errorcode)` tuple has hit a beautiful compromise, making it possible, and idiomatic, to handle errors (or actually, messages in general) as close as possible to where they happen, avoiding teleconnections between otherwise disparate code sections. With C++17 **structured bindings** a similar approach can be taken in C++.

This or that is, however, an implementation detail - and in general I opened this issue for discussion, and in order to ensure that @rouault's remarks do not rot away in the darkness of a comment in a merge-commit.

Regarding the dicerning between *persistent and transient* errors: I looked into this some years ago, and couldn't really make sense of it either.

In my humble opinion, **persistent** errors are the errors that are detected during instantiation of the `PJ` object, while **transient** errors are the ones detected while using the `PJ` for actual work. With this delineation we don't have to worry about persistent errors outside of `PJ` constructors, and we need not do anything else with them than returning a `nullptr`

**Comment by rouault** [comment]
Persistent vs transient errors was a pj_transform()-only concept, but we might face the same problems with the proj_trans() family.

One thing that should be defined is how we want some API to work regarding errors, in particular proj_trans_array() and proj_trans_generic(). I assume that we wouldn't want an error for point n°0 (for example due to a point being outside the validity area of a projection and failing for example in the projected->geographic inversion) to cause errors on point n°1 ? I'm not sure what the behaviour is currently, if it is consistent, and if that's tested at all.

Regarding errors during instantiation vs coordinate transformation-time, things become a bit fuzzy with RFC4 and network enabled. For performance reasons, for example when doing a NAD83->NAD83(HARN) transformation where there are as many grids as US states, we don't want the creation of the pipeline to actually try to open the grid from the network, whereas in most cases only one particular pipeline and grid will be selected at proj_trans() time. So with RFC4 (restricted to the case of networking enabled), grid loading is defered, and thus what used to be an instantiation specific error (grid missing) can become a coordinate transformation-time error.

Classic C++ exceptions can work just fine, but with some conditions. I used them extensively in ISO-19111 code, because it was a completely new code part with little interaction with the C code base, and using only modern C++ object creation with smart pointers; thus memory leaks - by design - couldn't happen even in the exception code paths. But for "PROJ classic" things are more tricky because we also a lot of C-style memory allocations.

**Comment by busstoptaktik** [comment]
> But for "PROJ classic" things are more tricky because we also a lot of C-style memory allocations.

A main reason for my recent comment about the value of "going full C++". Modern (post 11) C++ is absolutely beautiful: Virtually "Python with static typing". But again: Full C++ification of the classic code base is a major undertaking, touching large parts of the code base, and not providing any application level advantages (other than, presumably, an overall more stable, and easier maintained,  library).
