### ISSUE TITLE
The projections list is too deep in the website

### ISSUE THREAD

**Issue by hobu** [OSGeo/PROJ#1943]
I have to dig to find the projections list in the website. It's the thing that most people search for most of the time, and it takes clicking around non-obvious names (Coordinate operations) to find them. Consider moving them up a level.

**Comment by kbevers** [comment]
It is probably a good idea to so, yes. Could you outline how you'd like the structure to be? A worry I have is that simply dropping the "coordinate operation" level will leave the top level too crowded with individual chapters on projections, transformations, conversions and the pipeline operator.

Also, a change like this should implement redirects in sphinx, so that users trying to reach an old URL to a projection is forwarded to the correct place.

**Comment by busstoptaktik** [comment]
Perhaps just rename the top level entry to "Projections and other coordinate operations", to increase visibility/discoverability?
