### ISSUE TITLE
man pages ASCII input and output quote

### ISSUE THREAD

**Issue by jidanni** [OSGeo/PROJ#2029]
cs2cs man page says

>      when both input and output are ASCII all trailing portions of
>      the input line are appended to the output line.

Well,

```
cs2cs EPSG:4326 EPSG:32631 <<EOF
45N 2E zzzzzzzzzz我
EOF
```
worked fine, even though not ASCII, so perhaps just say instead:

>      all trailing portions of the input line are appended to the
>      output line.

**Comment by busstoptaktik** [comment]
@jidanni, this will work as long as the encoding is UTF-8. However, for any other encoding a stray null will terminate the output. So your suggestion really doesn't improve on the correctness.

Through the ingenious design of UTF-8, PROJ handles at least most cases of UTF-8, although in its basline design being ASCIIdious. Getting this description 100% right is not an easy task - although a pull request with a more all-encompassing description will definitely be welcomed - but expect quite a lot of discussion and testing necessary in order to arrive at something better than what we have now.

Closing, but suggesting you submit a PR for discussion.
