### ISSUE TITLE
PROJ very outdated on the Ubuntu package archive?

### ISSUE THREAD

**Issue by nick-youngblut** [OSGeo/PROJ#2311]
I'm trying to install PROJ >=6 (as a dependency for [gdal](https://github.com/OSGeo/gdal/tree/master/gdal)), and it appears that the [latest version on debian](https://packages.ubuntu.com/bionic/science/proj-bin) is 4.9.2 (for Ubuntu 16 or 18). Is this correct, and if so, will PROJ be updated anytime soon?

**Comment by rouault** [comment]
Yes, they are still shipping older versions, which is expected given when PROJ 6 was released compared to the freeze of those Ubuntu versions + the transition to PROJ 6 has been a bit difficult due to the need of adapting downstream components. ubuntugis-unstable has PROJ 7 for bionic: https://launchpad.net/%7Eubuntugis/+archive/ubuntu/ubuntugis-unstable/+packages?batch=75&memo=75&start=75
