### ISSUE TITLE
Z-Coordinates not converted in newer versions for EPSG:31370 to EPSG:4326

### ISSUE THREAD

**Issue by aaron012** [OSGeo/PROJ#2318]
**Description**
When converting coordinates between  EPSG:31370 and EPSG:4326 the z-coordinates are not converted anymore. In older versions of the library, this was the case. Another coordinate system that we found where this happened is EPSG:2039. 

**Minimal example**:
```bash
docker run osgeo/proj:5.2 sh -c "echo 171160.576105325 172833.962098988 -33.041749736 | cs2cs -f \"%.9f\" +init=epsg:31370 +to +init=epsg:4326"
# Output: 4.669339658	50.865500371 10.000165402

docker run osgeo/proj:7.1.0 sh -c "echo 171160.576105325 172833.962098988 -33.041749736 | cs2cs -f \"%.9f\" +init=epsg:31370 +to +init=epsg:4326"
# Output: 4.669339464	50.865500746 -33.041749736
```

As you can see in the example in version 5.2 the z-coordinate is converted from -33.041749736 to 10.000165402. In version 7.1.0 the z-coordinate stays exactly the same as in the input.

**Comment by rouault** [comment]
EPSG:31370 and EPSG:4326 are 2D CRS. PROJ >= 6 will transform the Z component only if the two CRS have a Z component

Such a transformation can be used by first researching available transformations with:
```
projinfo -s EPSG:31370 -t EPSG:4979 --3d -o PROJ
```
and, for example selecting the second one listed in the above output:
```
echo "171160.576105325 172833.962098988 -33.041749736" | cct +proj=pipeline +step +inv +proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=51.1666672333333 +lat_2=49.8333339 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +step +proj=cart +ellps=intl +step +proj=helmert +x=-106.8686 +y=52.2978 +z=-103.7239 +rx=-0.3366 +ry=0.457 +rz=-1.8422 +s=-1.2747 +convention=coordinate_frame +step +inv +proj=cart +ellps=WGS84 +step +proj=unitconvert +xy_in=rad +z_in=m +xy_out=deg +z_out=m +step +proj=axisswap +order=2,1
```

**Comment by aaron012** [comment]
Thanks for the very quick response! Then it is indeed not a bug, my apologies. 
I do not completely understand the conversion yet, since EPSG:31370 is still a 2D CRS in the projinfo command? 
If there is any documentation on the 2D/3D CRS conversions you can point me to that would be a great help.

**Comment by rouault** [comment]
> is still a 2D CRS in the projinfo command?

The --3d switch in projinfo promotes both input and output CRS to a 3D version with a vertical axis with meter units, before researching coordinate operations between them.

**Comment by EvertEt** [comment]
Is this behaviour (`where its vertical axis is the ellipsoidal height in metres, using the ellipsoid of the base geodetic CRS.`) the same that happened in GDAL 2?

**Comment by EvertEt** [comment]
@rouault I am a bit confused why it does still happen converting to 4978.


31370 -> 4326: no z conversion
```
docker run osgeo/proj:7.1.0 sh -c "echo 171160.576105325 172833.962098988 -33.041749736 | cs2cs -f \"%.9f\" +init=epsg:31370 +to +init=epsg:4326"
4.669339464     50.865500746 -33.041749736
```
31370 -> 4978: z conversion
```
docker run osgeo/proj:7.1.0 sh -c "echo 171160.576105325 172833.962098988 -33.041749736 | cs2cs -f \"%.9f\" +init=epsg:31370 +to +init=epsg:4978"
4020239.660202931       328358.079520147 4924089.058669401

```
> PROJ >= 6 will transform the Z component only if the two CRS have a Z component

Based on this, since 31370 is 2D, I would expect no changes in both cases. Could you explain where this difference comes from? Thank you!

**Comment by rouault** [comment]
> Could you explain where this difference comes from? Thank you!

EPSG:4978 is a Geocentric CRS, so when expressing coordinates in it, you have no choice to also return a Z value (which is the position in metre of the point relative to the equatorial plane), otherwise that would be useless. But there should be no ellipsoidal height change due to datum transformation

**Comment by EvertEt** [comment]
I understand now, thank you, it indeed makes sense it has to happen here (since Geocentric CRS has to be 3D, 2D would just be the equatorial plane as you mentioned)
So there is an implicit conversion of 31370 to 3D happening here, right? Would it be the same as converting from whatever `projinfo EPSG:31370 --3d` outputs to 4978? (If I'm connecting the dots correctly, --3d would add a third axis specifying the ellipsoidal height in meters?)

**Comment by EvertEt** [comment]
@rouault Sorry for bumping this issue again but I would like to verify something. 

> PROJ >= 6 will transform the Z component only if the two CRS have a Z component

```
docker run osgeo/proj sh -c "echo 670309.67 4564479.054 756.734 | cs2cs EPSG:25830 EPSG:3857" && docker run osgeo/proj sh -c "echo 670309.67 4564479.054 756.734 | cs2cs EPSG:25830+5773 EPSG:3857"

-107805.14      5043925.64 756.73
-107805.14      5043925.64 807.39
```
Here I expected the result to be the same, since EPSG:3857 is 2D (according to https://epsg.io/3857 `Coordinate system: [Cartesian 2D CS](https://epsg.io/4499-cs)`).

But since the result is transformed in the second case, both of them are 3D then, could you help me understand the difference? (Same goes for 31370 mentioned above, so I think the main question is about why there is a z transform going to EPSG:3857 (or EPSG:4326, same behaviour). 

Thank you in advance.

**Comment by rouault** [comment]
> PROJ >= 6 will transform the Z component only if the two CRS have a Z component

This area is complex and I must confess I generally have troubles to predict how the code I've written always behave in all situations. See https://github.com/OSGeo/PROJ/pull/3119 for an analysis and a proposed fix/change of behaviour
