### ISSUE TITLE
Runtime "Fused Multiply Addition" check in tmerc.cpp causes segmentation faults on CentOS 7

### ISSUE THREAD

**Issue by DalePAtSafe** [OSGeo/PROJ#2326]
On CentOS-7 if libproj is linked into a python module and that python module is imported, a segmentation fault can occur. This is most easily observed simply by attempting to import libproj as a python module, the expected behaviour in that case is an ImportError from the python interpreter, but on platforms affected by this issue a segmentation fault will occur instead.

To be clear this issue will also occur if a real python module that links libproj is imported, the above is just the simplest way to reproduce the segfault.

I've traced the problem to [this commit](https://github.com/OSGeo/PROJ/commit/b84c9d0cb61f3bd561da6092e15e294ae7e410e0) which introduced a compiler generated runtime check for Fused Multiply Addition support in `src/projections/tmerc.cpp`. Removing the `BUILD_FMA_OPTIMIZED_VERSION` macro resolves the issue on affected platforms.

#### Current Output
```bash
$ PYTHONPATH=<dir containing libproj> python3
>>> import libproj
Segmentation fault (core dumped)
```

#### Expected Output
```bash
$ PYTHONPATH=<dir containing libproj> python3
>>> import libproj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_libproj)
```

#### Environment Information
 - PROJ 7.1.0 (and any version after the linked commit)
 - CentOS 7.8.2003
 - GCC 8.3.1
 - Python 2.7.5 or Python 3.6.8

#### Installation method
 - Built from source

**Comment by rouault** [comment]
What is this libproj python module ? Where does it come from ?

**Comment by rouault** [comment]
> What is this libproj python module ? Where does it come from ?

answering myself: ok, you are probably just trying to import libproj.so as if it were a true python module, for the sake of reproducing the real issue

**Comment by DalePAtSafe** [comment]
Yes, the real way this ends up affecting us is that it causes one of our real python modules that indirectly links to libproj to crash on import, but it turns out that the issue is easily reproduced just by trying to import libproj.so as if it were a python module.

**Comment by rouault** [comment]
OK, I could reproduce the issue with a simple program that just does dlopen("src/.libs/libproj.so", RTLD_NOW) and this crashes in the dynamic loader library. So I believe this is a bug of the dynamic loader library on CentOS 7 or a bug with its use with a modern compiler such as gcc 8.3.

I don't think this can be detected at configure time unfortunately. I tried a simplified test program that simulates what tmerc.cpp does
```
__attribute__((target_clones("fma","default"))) inline static double test_internal(double a, double b, double c)
{ return a * b + c; }

double test(double a, double b, double c) { return test_internal(a,b,c); }
```
but when loaded with dlopen() things work fine. So no simple reproducer.

@kbevers Any opinion if we should disable this BUILD_FMA_OPTIMIZED_VERSION optimization ? I would lean into that. I don't remember the figures. It was interesting to get, but the gains were modest and probably not worth the troubles.

**Comment by rouault** [comment]
I'd note I could reproduce only on CentOS 7. On Ubuntu 16.04 with gcc 8.2, loading libproj works fine

**Comment by ravenAtSafe** [comment]
Not sure if it helps at all, but we *were* able to load libproj on CentOS 7 as long as dlopen wasn't explicitly involved anywhere in the chain of libraries between it and the executable.

e.g. No crash if `myexe` links against `libmyshared.so` which links against `libproj.so`

**Comment by kbevers** [comment]
> @kbevers Any opinion if we should disable this BUILD_FMA_OPTIMIZED_VERSION optimization ? I would lean into that. I don't remember the figures. It was interesting to get, but the gains were modest and probably not worth the troubles.

It would be nice to determine the root cause of the problem. Is it a problem with the CentOS toolchain or PROJ? I can't help with that but having a clear answer to that makes it a lot easier to make a decision. 
Can the optimization be turned into a user configurable build option? In that case we can let CentOS users build a slightly slower PROJ without making everyone elses tmerc go a little bit slower.

**Comment by rouault** [comment]
> No crash if myexe links against libmyshared.so which links against libproj.so

Yes, I could run the PROJ test suite fine. Really related to using dlopen(), such as done in Python module loading.

> Is it a problem with the CentOS toolchain or PROJ?

I'm afraid this is beyond my knowledge / time I want to spend. It crashes somewhere in the dlopen() code, so technically I'd say this is a bug of the OS (or more exactly this is a bug of glibc, or perhaps an incompatible combination of the old glibc of CentOS 7 with a modern gcc), since it should at worse return a clean error, not crash. But which versions of glibc are affected would require a lot of testing, and it is actually more a runtime issue than a build time one.

> Can the optimization be turned into a user configurable build option? In that case we can let CentOS users build a slightly slower PROJ without making everyone elses tmerc go a little bit slower.

It could be turned in / out, but I'm not sure I won't to go into that complexity (would need to go in autotools and cmake...). People that want the maximum performance for their CPU can build PROJ with CXXFLAGS="-march=native -O2". The runtime selection using this GCC feature was a nice to have, but it looks it turns out to be more a headache. Especially since the optimization was for the approx tmerc code, which is not used by default.

**Comment by kbevers** [comment]
@rouault You make good arguments for turning this optimization off. Go ahead :-)
