### ISSUE TITLE
Database: upgrade to EPSG version 10 data model

### ISSUE THREAD

**Issue by jmckenna** [OSGeo/PROJ#2355]
- today the new EPSG database model 10 is available for download, version 10.0.0.1 (https://epsg.org/whatsnew.html)
 - the purpose of this ticket is to track the changes required to adapt the PROJ db scripts for this new EPSG data model
 - note that version 10.0.0.1 has no data changes from 9.9/9.9.1, so there is no direct effect on PROJ today, other than beginning to prepare for the new model changes.  All future database releases will be with this ISO 19111:2019 model.
- more info about the model changes: https://epsg.org/data-model-changes.html

**Comment by rouault** [comment]
That's something I should be able to start working on soon, thanks to funding I've managed to gathered from a few sponsors

**Comment by jmckenna** [comment]
That's great news about funding!  I was wondering if I was going to have to spend my weekend on learning this ha.  Glad to hear.

**Comment by rouault** [comment]
Besides the database structure changes, that should remain mostly PROJ internal "details", there is one change that will be visible from the outside. EPSG v10 now supports the concept of Datum Ensemble, e.g "WGS 84" is no longer a single datum but the set of the 6 realizations of it.

So https://epsg.org/crs/wkt/id/4326 now outputs
```
GEOGCRS["WGS 84",
  ENSEMBLE["World Geodetic System 1984 ensemble",
     MEMBER["World Geodetic System 1984 (Transit)",
       ID["EPSG",1166]],
     MEMBER["World Geodetic System 1984 (G730)",
       ID["EPSG",1152]],
     MEMBER["World Geodetic System 1984 (G873)",
       ID["EPSG",1153]],
     MEMBER["World Geodetic System 1984 (G1150)",
       ID["EPSG",1154]],
     MEMBER["World Geodetic System 1984 (G1674)",
       ID["EPSG",1155]],
     MEMBER["World Geodetic System 1984 (G1762)",
       ID["EPSG",1156]],
     ELLIPSOID["WGS 84",6378137,298.257223563,
      LENGTHUNIT["metre",1,ID["EPSG",9001]],
      ID["EPSG",7030]],
     ENSEMBLEACCURACY[2],
    ID["EPSG",6326]],
  PRIMEM["Greenwich",0,
    ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9102]],
    ID["EPSG",8901]],
  CS[ellipsoidal,2,
    ID["EPSG",6422]],
  AXIS["latitude (Lat)",north,
    ORDER[1]],
  AXIS["longitude (Lon)",east,
    ORDER[2]],
  ANGLEUNIT["degree (supplier to define representation)",0.0174532925199433,ID["EPSG",9122]],
  USAGE[SCOPE["Horizontal component of 3D system."],AREA["World."],
  BBOX[-90.00,-180.00,90.00,180.00]],
ID["EPSG",4326]]
```
whereas current PROJ outputs:
```
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["unknown"],
        AREA["World"],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]
```

PROJ >= 6 can ingest the WKT formulation using the ENSEMBLE[] node, however the CRS -> CRS operation computation logic of current PROJ version is not ready to deal with DatumEnsemble. For example if you do "projinfo -s @the_wkt_with_WGS84_ensemble.wkt -t EPSG:26711", PROJ will create a dummy ballpark transformation between the WGS 84 datumensemble and NAD27. So fixing this is part of the work.

But this raises a question about backward compatibility: if PROJ 7.2 (assuming this is ready for it) outputs ENSEMBLE[] for WGS84 for WKT2:2019, and someone uses that WKT in older PROJ versions, this will not work properly as mentioned above.
Should we care about that scenario ? If not, then all well. Otherwise, we'd have to introduce a new WKT flavor WKT2:2019:NO_ENSEMBLE or something like that, for people that would badly need to output WKT without ensemble. I'm not sure we need to go into that complication, but opinions welcome (@kbevers @hobu)

**Comment by kbevers** [comment]
> But this raises a question about backward compatibility: if PROJ 7.2 (assuming this is ready for it) outputs ENSEMBLE[] for WGS84 for WKT2:2019, and someone uses that WKT in older PROJ versions, this will not work properly as mentioned above.
Should we care about that scenario ?

I think it is reasonable to not care about that scenario. The fact that PROJ doesn't output the WGS84 ENSEMBLE[] for WKT2:2019 can even be considered a bug, so this would simply be a bug fix that makes PROJ follow the standard more correctly.

**Comment by hobu** [comment]
> I think it is reasonable to not care about that scenario.

Most people don't even know this is an issue, and we have beaten up our users "for their own good" quite a bit the past few years. I would prefer this change to be 8.0 stuff and we do a 7.1.x that accommodates ENSEMBLE consumption (would it simply map it to old 4326?). The only ENSEMBLE that really matters for most people is 4326. 

Is there to be a WKT3 with the work on geodetic shifting going on?

**Comment by rouault** [comment]
What could be done is have the C constant PJ_WKT2_2019 mapped to a new C++ WKTFormatter::Convention::WKT2_2019_NO_ENSEMBLE constant in PROJ 7.2 . And in PROJ 8 we'd just switch it to WKTFormatter::Convention::WKT2_2019 (with ENSEMBLE[]). That way PROJ C users won't be affected in the 7.x series regarding WKT export.

> would it simply map it to old 4326?

yes the idea is to emit DATUM[] in compatibility mode (will be needed for WKT1 export anyway). Identification will be done through the datum/datumensemble code (since in EPSG, a datumensemble is modelled as an "extension" of a datum AFAICS) when present. When absent, this will be more tricky. We'd have to add some mapping if there's no existing alias in the DB.

> The only ENSEMBLE that really matters for most people is 4326.

ETRS89 is now going to be a ensemble in EPSG. And there will be more in the future

> Is there to be a WKT3 with the work on geodetic shifting going on?

Do you mean the GGXF and/or deformation model groups ? I'm not aware of WKT impacts for them

**Comment by jmckenna** [comment]
10.003 was released yesterday, which they state is the "first official release with the new data model".
