### ISSUE TITLE
[8.0.0] Behaviour change (tolerance condition error)

### ISSUE THREAD

**Issue by Algunenano** [OSGeo/PROJ#2413]
Comes from Postgis trac: https://trac.osgeo.org/postgis/ticket/4785

We are seeing a behaviour change in our regress tests and I'm unsure if this a expected change or not.
 
#### Problem description

When doing the following transformation `ST_Transform('SRID=4326;POINT(180 90)'::geometry, 3395)` or using cs2cs: 

```
cs2cs EPSG:4326 EPSG:3395
90 180
```

The old behaviour (7.2/HEAD):
```
*       * inf
```

Which in Postgis shown as and error `transform: tolerance condition error (-20)`.

Under master/HEAD (8.0.0), we are seeing a new behaviour:
```
20037508.34     242485887.61 0.00
```

So my question is whether we should consider this a valid output going forward and adapt the tests for it.

#### Environment Information
 - 7.2 vs master
 - Archlinux

#### Installation method
 - Built from source from master/HEAD and 7.2/HEAD. Both using proj-data-1.3.

**Comment by rouault** [comment]
This is a consequence of https://github.com/OSGeo/PROJ/pull/2397 . It turns out that 90 deg latitude which projects to infinity in Mercator isn't actually reached after conversion to radians (value slightly below PI/2), so that point can actually be projected.

I'd suggest Postgis tests to not use that test point. Mercator at such high latitude doesn't make sense, be it a big finite value or a infinite value.

If you want to test error conditions, I fail to come with a practical reliable alternative. I was going to suggest a north polar stereographic projection and try to reproject a point in the southern hemisphere, but PROJ allows that currently (shouldn't). The orthographic projection in similar situation has checks, but there's no EPSG code with a orthographic projection.

```
$  echo -10 0 | src/cs2cs EPSG:4326 +to "+proj=ortho +lat_0=90 +type=crs"
*	* inf
```

Hum actually I could find one with the Transverse Mercator projection. PROJ will for example fail on :
```
$ echo 0 95 | src/cs2cs EPSG:4326 EPSG:32631
*	* inf
```
(it could theoretically be improved but that would require using the 'exact' Transverse mercator formulas, which would be a big task for little practical gain)

**Comment by Algunenano** [comment]
Since this specific Postgis test comes from a 9yo issue with internal caches and pj_get_errno_ref, it doesn't matter which projections it uses just that it works with valid data after a failure. I'll try changing it to 32631.

Thanks a lot.
