### ISSUE TITLE
cct can't instantiate operation given as urn:ogc:def:coordinateOperation:auth::code

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#2418]
For instance

```
$ PROJ_LIB=./data/ ./src/cct -vvv urn:ogc:def:coordinateOperation:EPSG::8366
lt-cct: Running in very verbose mode
pj_open_lib(proj.db): call fopen(./data//proj.db) - succeeded
proj_create: unrecognized format / unknown name
lt-cct: Bad transformation arguments - (generic error of unknown origin)
    'lt-cct -h' for help
```

`cct` fails because the logic in `src/apps/optargpm.h` is build to read input on a specific form as specified in the documentation:

https://github.com/OSGeo/PROJ/blob/848ee7b6a8bf56a9d967f104ba2ef2ad92dc48d5/src/apps/optargpm.h#L27-L48

The failure here obviously comes from not supplying +-options such as `+proj=merc`. 

Ideally `cct` would be able to accept input like `urn:ogc:def:coordinateOperation:EPSG::8366` without failing. It is not entirely clear to me right now how that is best achieved. It will probably be either by circumventing `optargpm`-mechanisms when not +-options are added or by modifying `optargpm` to allow input like `urn:ogc:def:coordinateOperation:EPSG::8366` instead of +-options.

The benefit of fixing this is that it will be much easier to search for a specific transformation using `projinfo` and then pasting the operation EPSG-code into `cct` instead of the complete pipeline (that potentially is quite long and not copy-paste friendly).

**Comment by busstoptaktik** [comment]
... it feels like an eternity since I wrote optargpm and cct - but apparently it's only 3 years...

I see what you are doing over at #2419, but I believe the cleanest way to do this will be to introduce the option `--urn`, so you can write: `--urn=urn:ogc:def:coordinateOperation:EPSG::8366`.

This will keep the pattern matching inside the optargpm logic, and buy you a bit of functionality for free, while not introducing any new syntax elements.

**Comment by kbevers** [comment]
Yes, that's another possibilty. I don't have strong feelings for either solution. I was going for something that emulates what can be put into [`proj_create`](https://proj.org/development/reference/functions.html#c.proj_create) although that is not entirely suitable in the case of `cct`. 

If a new option is introduced I would probably change the logic slightly so that the `urn:ogc:def:coordinateOperation:` bit is optional. So you could do

```
cct --urn EPSG:8366
```

Not sure if `--urn` is the best name for the since there's a bunch of non-coordinateOperation URN's that would make sense to pass to `cct`. Perhaps `--operation` or `--op`?

**Comment by rouault** [comment]
It would be good to be able to directly use ``cct EPSG:8366`` or even by name ``cct "ITRF2014 to ETRF2014 (1)"`` like projinfo allows

**Comment by kbevers** [comment]
I agree @rouault. Will `proj_create` accept input like that without modifications? Like, what happens if a EPSG-code is both a CRS and a coordinate operation?

**Comment by busstoptaktik** [comment]
> It would be good to be able to directly use `cct EPSG:8366` or even by name `cct "ITRF2014 to ETRF2014 (1)"` like projinfo allows.

That would definitely be awesome. One could try to throw argv[1] at proj_create, and if it sticks suppose that that is what the user wanted. But I would probably prefer an option (like `--op`, `--spec` or whatever), to make sure we do not misinterpret files named after the CRS in use...

**Comment by busstoptaktik** [comment]
(alternatively: use the option/file splitter `--` and throw everything preceding it at `proj_create()`)

**Comment by rouault** [comment]
> Will `proj_create` accept input like that without modifications? Like, what happens if a EPSG-code is both a CRS and a coordinate operation?

If using "EPSG:XXXX", proj_create() will instanciate a CRS. To instanciate a coordinate operation, you either need to use the urn:ogc:def:coordinateOperation: syntax (or use proj_create_from_database() with category = PJ_CATEGORY_COORDINATE_OPERATION )

**Comment by snowman2** [comment]
How pyproj does it [here](https://github.com/pyproj4/pyproj/blob/9ab0f5dbb51e0237e4a02187f5041afdedf78f7b/pyproj/_crs.pyx#L1827-L2116)

- [proj_create_from_database](https://github.com/pyproj4/pyproj/blob/9ab0f5dbb51e0237e4a02187f5041afdedf78f7b/pyproj/_crs.pyx#L1930) + `PJ_CATEGORY_COORDINATE_OPERATION`
- `proj_create_from_name` + PJ_TYPE [here](https://github.com/pyproj4/pyproj/blob/9ab0f5dbb51e0237e4a02187f5041afdedf78f7b/pyproj/_crs.pyx#L2103)
- `proj_create` + check type using `proj_get_type` [here](https://github.com/pyproj4/pyproj/blob/9ab0f5dbb51e0237e4a02187f5041afdedf78f7b/pyproj/_crs.pyx#L1983)

**Comment by snowman2** [comment]
pyproj tests [here](https://github.com/pyproj4/pyproj/blob/9ab0f5dbb51e0237e4a02187f5041afdedf78f7b/test/crs/test_crs.py#L610)

**Comment by kbevers** [comment]
> to make sure we do not misinterpret files named after the CRS in use...

I assume you mean operation, not CRS. The implementation in ffc4107 handles this. The first input that is recognized as a file by `optargpm` is regarded as the operation, the rest is processed as files as per the usual logic.

I'll modify my current code to use `proj_create_from_database` which hopefully should  make things a bit simpler. I'll look into that tonight.

**Comment by busstoptaktik** [comment]
> I assume you mean operation, not CRS

No - I actually mean CRS: The situation I hinted at is  when a file is named after the CRS in use *and* there's a transformation having the same number (which may happen since operations/tranformations and CRS are different namespaces in the EPSG registry).

I have no actual examples of this - just playing the devil's advocate to make sure no unintended consequences explode in our face in the future. I find this extension utterly awesome and right in the spirit of both `cct` (the program) and cct (the geodesist).

**Comment by kbevers** [comment]
So something like `cct ABCD:1234 ABCD:1234`? Where the first is the transformation in question and the second is a file containing coordinates? optargpm thinks both are filenames. If there are no +-options I take the first filename out of the list of filenames and treat it as input instead. The second will not be passed to a `proj_create`-function, so this shouldn't be a problem. The implemented logic may be wrong of cause but if I have managed to implement what I intended to, then there's now issue here.

**Comment by busstoptaktik** [comment]
The situation I considered also applied when there is only one file name: `cct REGISTRY:IDENTIFIER`. But in the code as it is now, you catch most cases of this situation by requiring `pargc` to be `0` before trying to instantiate through `proj_create_from_database()`.

This only leaves the situation where:

1. The file name can be mistaken for an operation from a registry, while:
2. The user forgot to specify the transformation using `+`-style args.

In this case we currently provide the error message "Bad transformation arguments", while in the new version, the instantiation will succeed, and `cct` will sit and wait for coordinates from `stdin`.

I think the usefulness of your addition far outweighs this minor change-of-behaviour. Especially since the situation will never occur on Windows based file systems, where `:` is not a valid part of a filename.

**Comment by busstoptaktik** [comment]
> Especially since the situation will never occur on Windows based file systems, where : is not a valid part of a filename.

(of course this claim is only valid until the day some evil person builds a registry with a single letter name: `a:gony`, `b:anana` and `c:ucumber` are perfectly valid filenames on FAT and NTFS)

**Comment by kbevers** [comment]
> The situation I considered also applied when there is only one file name: cct REGISTRY:IDENTIFIER.

It could be checked that the input name isn't a file before it is fed to `proj_create` or `proj_create_from_database` but my gut feeling is that this situation is probably not super likely so I don't think it is worth the hassle. Do you agree?

**Comment by busstoptaktik** [comment]
>  Do you agree?

Definitely!
