### ISSUE TITLE
how to specify the projection surface height in proj4 string?

### ISSUE THREAD

**Issue by xelmirage** [OSGeo/PROJ#2499]
I'm using proj4 in an actual project, which needs accurate projection calculation. To realize accurate projection, it defines a projection surface height, which is calculated from the average altitude of the working zone. It is like, for example: 

If the projection surface height is 100m, and I'm using WGS84 datum, I have to add 100m to an of the datum and maintain the eccentricity(e) of the datum, which will make the b become (a+100)(1-f), where f=1/298.257222101

Now my working solution is directly using the a and b computed as mentioned above in the string, like

`+proj=tmerc +lat_0=0 +lon_0=30 +k=1 +x_0=500000 +y_0=0 +a=6378237.0 +b=6356852 +units=m +no_defs `

where `+a=6378237.0` means the a of WGS84(6378137.0) plus 100m, `+b=6356852` means 6378237.0*(1-1/298.257222101), f is the oblateness of WGS84 datum.

Now I'm wondering is there any parameter in the proj4 string that can let me directly specify the projection surface height directly, instead of manually giving a and b? something like `+proj_surface_height=100m` ?

**Comment by busstoptaktik** [comment]
@xelmirage: No, there is no such parameter. I suppose you need it in order to get improved distance metrics on the projected surface, but I am not sure this is the optimum way to achieve that: You will have to provide additional details of what you are actually doing, and trying to achieve.

This is, however, not the proper forum for that kind of discussions, so take it to the PROJ mailing list (to sign up, see [this page](https://lists.osgeo.org/mailman/listinfo/proj)).

Here on Github, you are reaching out to the PROJ developers, which is the proper thing to do if you have discovered a bug, or have a suggestion for improvement. In both cases it will be a good thing to raise the discussion on the mailing list, to be reasonably sure there is not a better way of solving the problem, before littering the issue tracker with non-issues.
