### ISSUE TITLE
Mention "[cct|cs2cs]" etc. on ALL examples

### ISSUE THREAD

**Issue by jidanni** [OSGeo/PROJ#2632]
In the PDF manual we see e.g.,
```
+proj=pipeline+step +proj=tmerc +lat_0=42.5 +lon_0=-72.5 +k_0=0.999964286 +x_0=500000.00001016 +y_˓→0=0+step +proj=unitconvert +xy_in=m +xy_out=us-ft
```
*Please* add "cct" or "proj" or "cs2cs" or "[cct|cs2cs|gie]" etc. to the front of each of
 these, so we don't need to test to reverse engineer by trial and error
 testing, to figure out what which one(s) are meant. Thanks.

OK, via trial and error, I have determined that the example
``` 
+proj=axisswap +order=4,3,2,1
```
needs to have cct at front. Same with all four in that group.
But that's just the tip of the iceberg.

Yes sometimes we see
```
Note:Can not be used with the proj application
```
well that is good, but still there are several applications there that you provide in /usr/bin so please be explicit on each example. Thanks.

Maybe even add a prompt, '$', to the front of them too.

**Comment by kbevers** [comment]
It's written like this by design. These are all valid inputs to API functions such as `proj_create()` and friends. Expressing all the various places a given projstring can be used will just clutter the docs. The examples are expressed in terms of PROJ's internal "transformation language" which can be applied in many different scenarios. It is likely that this can be explained better somewhere in the docs (suggestions are welcome) but the suggestion in this issue is not the solution.
