### ISSUE TITLE
Kavrayskiy vs. Kavraysky vs. Kavraisky: typo or alternative transliteration?

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/PROJ#2670]
Wikipedia has an article [Vladimir V. Kavrayskiy](https://en.wikipedia.org/wiki/Vladimir_V._Kavrayskiy) for the  Soviet geodesist and cartographer named in several projections. Meanwhile, encyclopedia.com has an article [Kavraysky, Vladimir Vladimirovich](https://www.encyclopedia.com/science/dictionaries-thesauruses-pictures-and-press-releases/kavraysky-vladimir-vladimirovich), which is spelled slightly different. PROJ consistently uses a third spelling variation: Kavraisky
```
$ git grep -i Kavrayskiy
$ git grep -i Kavraysky
$ git grep -i Kavraisky
docs/old/libproj.pdf:(Eckert III, Putnins P1, Putnins P'1, Wagner VI and Kavraisky VII.)
docs/source/operations/projections/kav5.rst:Kavraisky V
docs/source/operations/projections/kav5.rst:   :alt:   Kavraisky V
docs/source/operations/projections/kav5.rst:.. note:: All parameters are optional for the Kavraisky V projection.
docs/source/operations/projections/kav7.rst:Kavraisky VII
docs/source/operations/projections/kav7.rst:   :alt:   Kavraisky VII
docs/source/operations/projections/kav7.rst:.. note:: All parameters are optional for the Kavraisky VII projection.
docs/source/operations/projections/wag1.rst:Wagner I (Kavraisky VI)
docs/source/operations/projections/wag1.rst:   :alt:   Wagner I (Kavraisky VI)
src/pj_list.h:PROJ_HEAD(kav5, "Kavraisky V")
src/pj_list.h:PROJ_HEAD(kav7, "Kavraisky VII")
src/pj_list.h:PROJ_HEAD(wag1, "Wagner I (Kavraisky VI)")
src/projections/eck3.cpp:PROJ_HEAD(kav7, "Kavraisky VII") "\n\tPCyl, Sph";
src/projections/sts.cpp:PROJ_HEAD(kav5,    "Kavraisky V")         "\n\tPCyl, Sph";
src/projections/urmfps.cpp:PROJ_HEAD(wag1, "Wagner I (Kavraisky VI)") "\n\tPCyl, Sph";
test/gie/builtins.gie:# Kavraisky V
test/gie/builtins.gie:# Kavraisky VII
test/gie/builtins.gie:# Wagner I (Kavraisky VI)
```
Is PROJ using a legitimate transliteration from Каврайский? Or is PROJ using a historic typo?

**Comment by kbevers** [comment]
From Snyder's Map projections: A working manual, p. 111:

> Several Scot (Murdoch), Swiss (Euler), English (Everett), and Russian
(Vitkovskiy, Kavrayskiy, and others) mathematicians published papers between
1758 and 1934 describing means of selecting the two standard parallels so that
distortion is minimized using various criteria. Each of them used the same basic
conic projection with concentric circular parallels and straight meridians for radii
(Snyder, 1978a). The name of one ofthem, V. V. Kavrayskiy (or Kavraisky), has
been mistakenly applied in some U.S. literature to the basic projection, but his
contribution did not occur until 1934. 

There has probably been several transliterations of the original Russian/Soviet spelling floating around in the past. I think that is quite common. Is one version of the spelling more correct than the other?

**Comment by snowman2** [comment]
Кав -  kav
рай - ray
ский - ski

IMO "Kavrayskiy" seems to be the version most likely to be pronounced correctly.
