### ISSUE TITLE
compilation error on Universal Windows Platform

### ISSUE THREAD

**Issue by fugelen** [OSGeo/PROJ#2684]
When upgrading to proj 7.2.1 we discovered some issues when compiling for UWP (Universal Windows Platform):
```
 \proj\7.2.1\src\filemanager.cpp(695): error C3861: 'CreateFileW': identifier not found []
 \proj\7.2.1\src\filemanager.cpp(1215): error C2065: 'FOLDERID_LocalAppData': undeclared identifier []
 \proj\7.2.1\src\filemanager.cpp(1215): error C3861: 'SHGetKnownFolderPath': identifier not found []
 \proj\7.2.1\src\filemanager.cpp(1314): error C2065: 'GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS': undeclared identifier []
 \proj\7.2.1\src\filemanager.cpp(1315): error C2065: 'GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT': undeclared identifier []
 \proj\7.2.1\src\filemanager.cpp(1314): error C3861: 'GetModuleHandleEx': identifier not found []
```

We support a number of platforms, including UWP and wasm, and so it would be very useful if we could plug in our own portable file handling, and disable the filemanager.

**Comment by rouault** [comment]
> so it would be very useful if we could plug in our own portable file handling, and disable the filemanager.

That already exists as proj_context_set_fileapi(). You just need to submit a pull request to fix the compilation issue on UWP. I don't know UWP but I imagine it includes some kind of file API...

**Comment by rhuijben** [comment]
When compiling for UWP the filemanager should use CreateFile2() instead of CreateFileW(). As access to the shared application data is restricted I think the logical place to look for the proj.db file would be the application directory directly. 

In theory the proper location could be the application settings directory for the single project... but that is harder to maintain, while having it in the application would make things easy.

UWP runs the program in its own sandbox, so just placing things properly and then assuming things are there should work just fine.
