### ISSUE TITLE
Wrong version number in `project-proj-version.cmake`

### ISSUE THREAD

**Issue by dotlambda** [OSGeo/PROJ#2731]
#### Example of problem
I'm building PROJ 7.2.1 but get
```
set (PACKAGE_VERSION "7.2.0")
set (PACKAGE_VERSION_MAJOR "7")
set (PACKAGE_VERSION_MINOR "2")
set (PACKAGE_VERSION_PATCH "0")
```
in `project-proj-version.cmake`.

#### Problem description
QMapShack requires PROJ >= 7.2.1 and thus unexpectedly fails to build.

This is not a problem in version 8.0.1 (there `PACKAGE_VERSION` is set to `"8.0.1"`) and I would like to know which commit fixed it so I can apply a patch.

#### Expected Output
```
set (PACKAGE_VERSION "7.2.1")
set (PACKAGE_VERSION_MAJOR "7")
set (PACKAGE_VERSION_MINOR "2")
set (PACKAGE_VERSION_PATCH "1")
```

#### Environment Information
 - PROJ version: 7.2.1
 - Operation System: NixOS

#### Installation method
 - from source

**Comment by rouault** [comment]
I presume this is an oversight of the 7.2.1 release process. There's no fixing patch per se. The correct version number was set for the 8.0.0 release, but you don't want to apply it of course. So the fix is that you patch the proj_version() macro in the CMakeLists.txt file at the root of the 7.2.1 tarball.
