### ISSUE TITLE
DO NOT USE STALEBOT on bugs the team has not even looked at yet.

### ISSUE THREAD

**Issue by jidanni** [OSGeo/PROJ#2743]
DO NOT USE STALEBOT on bugs the team has not even looked at yet.
Thank you.

**Comment by kbevers** [comment]
The point of the stale bot is to close issues with no progress. If there's no progress it must mean that either no-one is interested in them anymore or there's insufficient information in them to proceed. If the reminder from the stale bot doesn't resolve that the issues should be closed. This is by design and will not be changed.

**Comment by jidanni** [comment]
Yes, but you forgot another possibility:
Nobody on the team ever even saw the bug report!

**Comment by busstoptaktik** [comment]
> Nobody on the team ever even saw the bug report!

I can assure you that this has been the case for exactly zero of the recently closed stale issues.

And as @kbevers has already said: *The point of the stale bot is to close issues with no progress*. This can happen for many reasons, but the reason **does not matter at all**: The sole point is to move non-progressing issues out of the queue, where they mask the visibility of issues with actual progress, to a separate place, where they can be dug out again, should means, interest and information merit so.

**Comment by jidanni** [comment]
Users might have spent hours composing a report. If the team could just spend one extra second to at least push the Eyeball Emoji, users (and other team members) could then determine if the report actually has been seen or not.
