### ISSUE TITLE
PROJ 8.0.1 breaks PCG94

### ISSUE THREAD

**Issue by dfileccia** [OSGeo/PROJ#2756]
I recently updated to PROJ 8.0.1 from PROJ 7.2.1 and the transform for Perth Coastal Grid 1994 quit working. I was notified by our Australian office of the 1 to 1.5 meter bust in the horizontal for both northing and easting.

All transforms convert from WGS84 to the desired projection.

I was able to track it down to some difference in PROJ 8 by rolling back to PROJ 7.2.1 and the issue disappeared. I was wondering if something has changed in the proj.db file that would cause this problem.

The expected result from  a popular survey package:
N32d 00m 55.7745s
E115d 55m 27.1455s
N: 256427.878m
E: 60160.117m

With PROJ 7.2.1 after rollback:
N: 256427.880m
E: 60160.118m

See images for results with PROJ 8.0.1.

I am not at liberty to give you the code for this but parameters came from the PCG94 from WAProjectionGrid.xls from the government of Western Australia.

EXCERPT from our Australian office.

PCG94 in GM 1.4.152 (dozer)
![image](https://user-images.githubusercontent.com/3809346/123838615-2c24a000-d8da-11eb-87dc-a0459e46178c.png)

PCG94 in GM 1.4.138
![image](https://user-images.githubusercontent.com/3809346/123838659-36df3500-d8da-11eb-9938-e4d0ec05b3c2.png)

PCG94 of VR500 primary antenna position with ********** ******* (as close as possible)
![image](https://user-images.githubusercontent.com/3809346/123838691-4199ca00-d8da-11eb-922c-5dee134e6812.png)
![image](https://user-images.githubusercontent.com/3809346/123838707-48284180-d8da-11eb-8279-2661918762b6.png)

This is an urgent issue because it is a previously working function that is now broken, that has a direct impact on machine accuracy rendering the system unusable until it is resolved, so I apologise for the hastiness, just know it is critical! We also need to understand where it has gone wrong, so we can ensure it is resolved in future versions also.

**Comment by rouault** [comment]
> the transform for Perth Coastal Grid 1994

the transform between which CRS to which CRS ? Can you give their EPSG codes ?

**Comment by dfileccia** [comment]
WGS84 Lat/Lon/Height (EPSG:4326) to Perth Coastal Grid 1994 (EPSG:8011).

I have tried with WKT strings too and it always comes down to 7.2.1 works and 8.0.1 does not.

**Comment by rouault** [comment]
> WGS84 Lat/Lon/Height (EPSG:4326) to Perth Coastal Grid 1994 (EPSG:8011).

I suspect you meant EPSG:8031 "GDA2020 / PCG2020", since EPSG:8011 "Perth Coastal Grid" is the conversion used by this CRS (but I see there's a ESRI:102216 "GDA_1994_Perth_Coastal_Grid_1994" that is GDA94 based, not GDA2020)

So, there's a GDA2020 to WGS 84 datum shift involved. In PROJ 7.2.1, the only transformation between those 2 datums is EPSG:8450 "GDA2020 to WGS 84 (2)" which is a null transformation, with a 3 m accuracy
In PROJ 8, there are 2 new transformations "WGS 84 to GDA2020 (3)" which involves a Helmert shift and "WGS 84 to GDA2020 (4)" which uses the au_icsm_GDA94_GDA2020_conformal_and_distortion.tif grid. Both have also a 3 m accuracy. From the text comment, they seem to be intented for use cases where WGS 84 and GDA94 would have been considered the same, and they share the same transformation parameters as transformations from GDA94 to GDA2020.
From what I can see, PROJ 8 is not wrong in selecting those new operations given its intended logic (https://proj.org/operations/operations_computation.html#filtering-and-sorting-of-coordinate-operations)
The fundamental issue is that a transformation between a static CRS such as GDA2020 and a dynamic datum such as WGS 84 (whose coordinates vary over time), especially as WGS 84 EPSG:4326 is a datum ensemble, is always going to have a lots of indeterminates, hence the 3m inaccuracy advertized by EPSG, and may involve user interaction to select the best transformation according to external elements that PROJ cannot guess by itself (you can explore the available possibilites with ``projinfo -s EPSG:4326 -t EPSG:78031``)

I suspect you should just ask PROJ to transform between  GDA2020 (EPSG:7844) and EPSG:8031 "GDA2020 / PCG2020", to avoid any datum shift issue and have thus stable results across verions

echo -32.015492916666666667 115.9242070833333333 | cs2cs -d 3 EPSG:7844  EPSG:8031 
returns
60160.116	356427.880 0.000
with all recent PROJ versions

**Comment by dfileccia** [comment]
No, I meant PCG94 since that is what the customer is using and our Australian office wants it. I match all the WA data for the conversion. This still doesn't explain why PROJ 7 works and PROJ 8 does not with the same transform. I have actually been fine since PROJ 4 (about 2012).

All LLH are WGS84 from our receiver. This is fed through the transform to get the grid coordinate. No other transforms necessary. As stated earlier this worked in PROJ 7 and does NOT in PROJ 8. Using the same transform. This is a definite bug.

The transform MUST go from WGS84 to PCG94 and this is the current in use:

PROJCS["Perth Coastal Grid 1994, Australia, GDA 94 Datum, Meters",
    GEOGCS["GDA94",
        DATUM["Geocentric_Datum_of_Australia_1994",
            SPHEROID["Geodetic Reference System of 1980",6378137,298.2572221009132,
                AUTHORITY["EPSG","7019"]],
            AUTHORITY["EPSG","6283"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4283"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",115.8166666666667],
    PARAMETER["scale_factor",0.99999906],
    PARAMETER["false_easting",50000],
    PARAMETER["false_northing",3800000],
    UNIT["METER",1]]
    
Again, PROJ 7 has no problems. PROJ 8 does. If I have to change what I am doing, I need to know how to attack this as I am not a surveyor but an EE relying on your API to make it all work. I also cannot change existing customer data or tell them they need to change it.

I am using GDAL as the shell for all this. The transforms are simple SRC: WGS84, DST: PCG94 (above WKT) or any other destination with a WKT. I can handle the OSTN02/OSTN15 for UK, the new Netherlands, and all over the US without issue. It is just since changing to PROJ 8 we see this problem.

Since GDAL is using PROJ, it was easy to find where the problem emanates. I think there is something different in the PROJ.DB that could be causing it. I tried using the PROJ 7 DB and it said invalid format when I ran the software.

I guess, if there is "no bug" then I am doing something procedurally wrong. I do not have the depth of knowledge of the +proj chain to make sure existing usage works. Is there some flag I can set in the API to make it work like PROJ 7?

**Comment by dfileccia** [comment]
New info. I run EPSG:4326 and EPSG:8031 in both PROJ7 and PROJ8 and get the same results. I am wondering if the whole issue is centering around GDA94 vs. GDA2020? The WKT above works with PROJ7 but not PROJ8.

**Comment by rouault** [comment]
> No, I meant PCG94 

OK, trying with your WKT, I see that newer PROJ use transformations between GDA94 and WGS 84 where WGS 84 is assumed to be equivalent to GDA2020 (this is the reverse situation as my earlier analysis) and thus you get a transformation between GDA94 and WGS84 ~= GDA2020.

> I need to know how to attack this as I am not a surveyor but an EE relying on your API to make it all work.

Well, you need to read a bit about geodesy if you use PROJ :-), because PROJ is only a tool and cannot automate everything. Given your use case and what is available in the EPSG database, I'd say you'd be much better by asking a transformation from GDA94 to PCG94 instead of EPSG:4326 to PCG94, since the result you seem to expect is a result where GDA94 and EPSG:4326 are considered the same (that was the transformation used in PROJ 7).

An alternative would also be that you change the advertized accuracy in proj.db for the "GDA94 to WGS 84 (1)" null transformation to be slightly lower than 3.0, so it gets precedence over the transformations you don't want.
``sqlite3 proj.db "update helmert_transformation_table set accuracy = 2.99 where name = 'GDA94 to WGS 84 (1)'"``

> New info. I run EPSG:4326 and EPSG:8031 in both PROJ7 and PROJ8 and get the same results. 

I do get different results with PROJ 8.0.1 and 7.2.1.

With 7.2.1 (using "GDA2020  to WGS 84 (2)"):
``echo -32.015492916666666667 115.9242070833333333 | cs2cs -d 3 EPSG:4326 EPSG:8031``
outputs
60160.116	356427.880 0.000

With 8.0.1 (using "WGS 84 to GDA2020 (3)"):
60161.128	356429.364 0.000

>  I think there is something different in the PROJ.DB that could be causing it. 

proj.db is regularly refreshed from latest EPSG releases, and newer ones added new transformations betwen GDA94 and WGS84 and GDA2020 and WGS84.

**Comment by rouault** [comment]
Closing as I don't think there's any PROJ changes needed
