### ISSUE TITLE
Unused variable in PJ_krovak

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#377]
The C_x in PROJ_PARMS is initialized as latitude of true scale, but never used.

Could this be a bug or merely a leftover from some cut-and-paste?

**Comment by micahcochran** [comment]
The Krovak projection looks like it was submitted through the [mailing list](http://lists.maptools.org/pipermail/proj/2002-April/000304.html) in 2002, which made into the [repo a few days later](https://github.com/OSGeo/proj.4/blob/df6cc651f452bd965252bfe78a70b510347ed0fe/src/PJ_krovak.c) with atleast a few modifications (without the original's German? comments).

PROJ_PARMS C_x was in the original submission.

**Comment by kbevers** [comment]
The origal code has the exact same behaviour. My guess is that it is a relic from whatever projection code was used as a template.

In https://github.com/OSGeo/proj.4/pull/385 I've removed C_x and related code and everything seems fine without it. 

On a slightly related note, there is a few other minor issues with this code, like defining the eccentricity (squared) in a separate variable instead of using P->e and P->es.

**Comment by kbevers** [comment]
Fixed in https://github.com/OSGeo/proj.4/pull/385
