### ISSUE TITLE
Repository website URL points to outdated content

### ISSUE THREAD

**Issue by dg0yt** [OSGeo/PROJ#450]
The [repository's](https://github.com/OSGeo/proj.4) website URL at the end of the description is http://proj.osgeo.org/ which points to Github at the top but is outdated otherwise (".../proj-4.9.1.tar.gz: Current source release."). 

The [wiki frontpage in this repository](https://github.com/OSGeo/proj.4/wiki) seems to be the currently maintained website (".../proj-4.9.3.tar.gz: Current source release.").

**Comment by micahcochran** [comment]
The wiki page at http://proj.osgeo.org/ probably needs to be updated so that the top of it points to the new main website for PROJ.4: http://proj4.org/

**Comment by dg0yt** [comment]
The top of http://proj.osgeo.org/ is correct. But it is confusing to follow the link from github.com to http://proj.osgeo.org/ only to find out the maintained page is on github.com.

**Comment by kbevers** [comment]
I agree, it is confusing at the moment. We are in the process of moving all the information from proj.osgeo.org and the github wiki pages to proj4.org. So far the links hasn't been updated because there is still unique information on the old pages. When that is moved to proj4.org the links should be changed. It is not the most exciting work, so progress is slow. You are very welcome to help by submitting a PR with updates to proj4.org.
