### ISSUE TITLE
invalid transform returned by proj4 call

### ISSUE THREAD

**Issue by corinnebosley** [OSGeo/PROJ#476]
In a set of coordinates for a PlateCarree to PlateCarree transform, the top and bottom egdes of the coordinate set were returned as invalid:
```
cs2cs +a=57.29577951308232 +proj=eqc +ellps=WGS84 +to +proj=eqc +a=57.29577951308232 +ellps=WGS84 +lon_0=-1.875 <<EOF
-1.875 91.25   
9.375 91.25   
20.625 91.25   
EOF

Rel. 4.9.1, 04 March 2015
<cs2cs>: while processing file: <stdin>, line 1
pj_transform(): latitude or longitude exceeded limits
*	* 0.00
Rel. 4.9.1, 04 March 2015
<cs2cs>: while processing file: <stdin>, line 2
pj_transform(): latitude or longitude exceeded limits
*	* 0.00
Rel. 4.9.1, 04 March 2015
<cs2cs>: while processing file: <stdin>, line 3
pj_transform(): latitude or longitude exceeded limits
*	* 0.00

```

Whereas these coordinates were returned with a valid answer:
```
cs2cs +a=57.29577951308232 +proj=eqc +ellps=WGS84 +to +proj=eqc +a=57.29577951308232 +ellps=WGS84 +lon_0=-1.875 <<EOF
-1.875 79.84375
9.375 79.84375
20.625 79.84375
EOF

0.00	79.84 0.00
11.25	79.84 0.00
22.50	79.84 0.00
```

Would you be able to explain this to me please?

**Comment by kbevers** [comment]
Yes, this is easily explained by breaking the transformation down to its basic components. So what you are doing is equivalent to:

```sh
echo -1.875 91.5 | proj -I +a=57.2957 +proj=eqc  | proj +proj=eqc +a=57.2957 +lon_0=-1.875
```

I've shortened the ```+a``` value for clarity and removed the ```+ellps``` parameter since it doesn't work on spherical projections anyway (also setting ```+a``` and ```+ellps``` doesn't really make sense). 
If you look at the [documentation](http://proj4.org/projections/eqc.html) for ```eqc``` you'll see that it is an extremely simple projection. If you do the calculations by hand you'll soon realize that the coordinates you put in are unchanged by the inverse projection. That's the first call to ```proj``` in the above statement. Effectively that means that you trying to project a latitude that is out of bounds (you've crossed the north pole):

```
$ echo -1.875 91.5 | proj -I -f %2.4f +a=57.29577951308232 +proj=eqc
-1.8750	91.5000
$ echo -1.875 91.5 | proj -f %2.4f +a=57.29577951308232 +proj=eqc
*	*
```
