### ISSUE TITLE
Thread safety issue in pj_transform

### ISSUE THREAD

**Issue by liuj03** [OSGeo/PROJ#478]
Hi,

We encountered a multithreading problem with pj_transform.

We traced the problem to the first call to pj_transform. It attempts to initialise `gridlist` and `vgridlist_geoid` if they are not already initialised. There is a potential race condition between the initialisation of these grid lists and their subsequent access. The call to pj_acquire_lock in pj_gridlist_from_nadgrids does not solve the race condition. Consider the following sequence:

1. Thread 1 checks if `gridlist` is 0 and succeeds, so it enters pj_gridlist_from_nadgrids. Thread 1 acquires the lock. Thread 1 is suspended before `gridlist` is initialised.
2. Thread 2 checks if `gridlist` is 0 and succeeds, so it enters pj_gridlist_from_nadgrids. Thread 2 blocks on pj_acquire_lock.
3. Thread 1 resumes on pj_gridlist_from_nadgrids and initialises `gridlist`. Thread 1 then attempts to access `gridlist`.
4. Thread 2 resumes, acquires the lock and initialises `gridlist`.

We tried working around this issue by moving the initialisation of `gridlist` and `vgridlist_geoid` to pj_init_ctx. This seems to solve the multithreading issue.

Can the devs advice if my observations are correct?

Thanks

**Comment by busstoptaktik** [comment]
I remember having had similar thoughts looking through the code base some months ago. But I deferred doing something about it, since the intentions behind the proj thread safety strategy (largely implemented through the context subsystem) are still unclear to me: Apparently at least one of the intentions of the context subsystem is to implement a per-thread errno. This surprises me, since, in multithreaded systems, errno is supposed to be implemented as a thread-safe macro.

A pull request with your work would be much appreciated - it would also provide an excellent opportunity for a more in-depth discussion of the "proj thread safety" subject.

/Thomas

**Comment by busstoptaktik** [comment]
@liuj03: Are you considering a pull request?

**Comment by paulhanssen** [comment]
Hi,

I'm from the same company as @liuj03. I've put our changes in the following pull request for your review.

https://github.com/OSGeo/proj.4/pull/493

Thanks for this product.

**Comment by busstoptaktik** [comment]
Closing this, as using a PJ object on more than one thread is not supported (see discussion in #493)
