### ISSUE TITLE
configure file missing? 

### ISSUE THREAD

**Issue by mbannert** [OSGeo/PROJ#481]
When I get the tarball from http://proj4.org/download.html I get a `configure` file, when I clone from github I don't. Is this on purpose?

**Comment by hobu** [comment]
> Is this on purpose?

Yes.

``configure`` is a generated file that can vary depending on the autoconf/automake capabilities of the system it is being run on.  Use the ``autogen.sh`` to create a configure file for your specific configuration.

It is not in the source tree because we do not want to encourage patches against it, and it is easy for developers to make large changesets for that file simply due to the platform and versions of autoconf/automake they are running.
