### ISSUE TITLE
Brokenness in Projection documentation figures

### ISSUE THREAD

**Issue by QuLogic** [OSGeo/PROJ#513]
Something seems to be up with the figures that show the projections. I'm pretty sure these used to work correctly before. It seems like there's some kind of issue with clipping the grid lines.

Here are some current examples:

![](http://proj4.org/_images/alsk.png)

![](http://proj4.org/_images/gnom.png)

![](http://proj4.org/_images/gs48.png)

![](http://proj4.org/_images/krovak.png)

![](http://proj4.org/_images/labrd.png)
(Many others are blank like this.)

![](http://proj4.org/_images/ocea.png)
(Probably shouldn't be inverted.)

**Comment by kbevers** [comment]
> I'm pretty sure these used to work correctly before

Nope, this has been the case since they were introduced.

> It seems like there's some kind of issue with clipping the grid lines

Either that, or that the given projection is not suitable for mapping the whole globe at once.

All the figures are generated with the same [script](https://github.com/OSGeo/proj.4/blob/master/docs/plot/plot.py). It goes well in most cases but the ones you've pointed out need special attention. I have been meaning to fix that for a long time, maybe I should actually get round to it soon :-)

> (Probably shouldn't be inverted.)

Probably shouldn't, no. You could very well have stumbled on a bug here. I'll look into it.

**Comment by QuLogic** [comment]
> Nope, this has been the case since they were introduced.

Huh, weird, all the links are "visited" and I don't recall seeing this weirdness before.

**Comment by kbevers** [comment]
I've already fixed them locally, but I want to improve the overall looks of the figures before I push the changes. Hopefully I can find the time to finish that during the weekend.
