### ISSUE TITLE
Parameter +no_rot broken for +proj=omerc

### ISSUE THREAD

**Issue by poidl** [OSGeo/PROJ#523]
Hi, I just started using proj

`Rel. 4.9.3, 15 August 2016`

for numerical ocean modeling, and want to create oblique Mercator projections that align with "tilted" coastlines, i.e. coastlines that are neither oriented N-S nor W-E. The following command

`proj +proj=omerc +alpha=-45.00000 +lat_0=50.00000 +lonc=-141.00000`

works as expected to align the central line with e.g. the North American west coast. But if I want to look at the rotated frame using this (identical to above but with `+no_rot`)

`proj +proj=omerc +alpha=-45.00000 +no_rot +lat_0=50.00000 +lonc=-141.00000`

the picture is flipped along a line orthogonal to the central line. For example, the North American west coast is "horizontal" and the North American continent is in the upper part of the picture and the North-East Pacific in the lower part. This is all as expected, but the problem is that true North points to the right of the picture, while it should point to the left.

Do you have any suggestions how to fix this?

There is a follow-up question, in case this is not easy to fix: Do I understand correctly that it's easy to do the `+no_rot` part myself by just tossing the x,y coordinates of the output **without** `+no_rot` through a simple rotation matrix? If that's the case, then this issue might be low(er)-priority.

Thanks a lot for your help!
![figure_grid_rotation_tutorial_omerc_proj](https://user-images.githubusercontent.com/1216556/26868105-254c5aa4-4bab-11e7-9901-810c46d75079.png)

**Comment by kbevers** [comment]
[This old post from the mailing list](http://lists.maptools.org/pipermail/proj/2013-February/006575.html) suggest that you use `+gamma=0.0` instead of `+no_rot`. Please try that and confirm if it gives you the expected results

**Comment by kbevers** [comment]
Also, this bit of code from the `omerc` forward calculation suggest that the axes have been switched in the `+no_rot` case:

```
    if (Q->no_rot) {
        xy.x = u;
        xy.y = v;
    } else {
        u -= Q->u_0;
        xy.x = v * Q->cosrot + u * Q->sinrot;
        xy.y = u * Q->cosrot - v * Q->sinrot;
    }
``` 

I looked very briefly for a mathematical description of the projection but couldn't easily find an answer. The above mail list post suggests that there are some confusion about the intermediate coordinate system being left- or right-handed.

**Comment by poidl** [comment]
Thanks for your help! I tried

`proj +proj=omerc +alpha=-45.00000 +gamma=0 +lat_0=50.00000 +lonc=-141.00000`

and it yields a coordinate system whose y (!) axis is aligned with the center line. So that's rotated by 90 degrees. See figure below

![figure_grid_rotation_tutorial_omerc_proj](https://user-images.githubusercontent.com/1216556/26908427-fba1a55e-4c3d-11e7-8334-07789a7b97c1.png)

whereas I expected something closer to this (this is produced with a self-written version of [Snyder's (1987) spherical formulas (his p. 69/70)](https://books.google.com.au/books?id=nPdOAAAAMAAJ&pg=PA66&lpg=PA66&dq=spherical+oblique+mercator&source=bl&ots=f4yyfqTgfT&sig=dUGjC4UTkSset9fThvOcU_BnPh8&hl=en&sa=X&ved=0ahUKEwj5ob2Jw5TUAhVFH5QKHb4VDPAQ6AEILTAB#v=onepage&q=spherical%20oblique%20mercator&f=false) where I assume his beta to be equivalent to proj's +alpha)

![figure_grid_rotation_tutorial_omerc](https://user-images.githubusercontent.com/1216556/26908452-173fb7f6-4c3e-11e7-892d-7ffbc54ea378.png)

So the proj's projection itself seems fine, except for the rotation. But I think that's still a bug?

**Comment by poidl** [comment]
I just noticed another worrying thing, if I add 180 degrees to `+alpha`, which should yield the same projection (?), I get this figure, which seems to be a different projection:

`proj +proj=omerc +alpha=135.00000 +gamma=0 +lat_0=50.00000 +lonc=-141.00000`
![figure_grid_rotation_tutorial_omerc_proj](https://user-images.githubusercontent.com/1216556/26908880-d2129ad8-4c40-11e7-847a-efa26c7f1221.png)

**Comment by ralphtee** [comment]
_proj +proj=omerc +alpha=-45.00000 +lat_0=50.00000 +lonc=-141.00000_

a) 
First thing first - when you do not specify any ellipsoid (+ellps) or datum (+datum), then OSGeo4W/GDAL/OGR/QGIS defaults it to the WGS84 reference ellipsoid. So, discretion is advised.

b)
In Oblique Mercator, rotation is more apt termed _rectification_. For proj.4, when you do not specify +gamma, it defaults to +gamma=0. And, +gamma=0 does not mean no rectification - it means to rectify the uv plane (specifically the u-axis) to 12 o'clock with the centre of projection (141W 50N) as the centre of rectification.

After projecting (from the "aposphere") to the uv grid, but before rectification, the chosen azimuth of projection (now called the central line) will lie in horizontal orientation, the same as the u-axis. Rectifying the uv plane to +gamma=0 will cause the central line to lie in vertical orientation.

c)
Apparently, ogr2ogr (2.2.2) (and presumably gdalwarp as well) _ignores_ +no_rot and will compute a "suitable" gamma value for you if you do not specify +gamma. (Again, discretion is advised.)

d)
If you DIY-ed Snyder's spherical version of the oblique mercator- I assumed you are aware of the needs to first convert the ellipsoidal lats to isometric lats before you project.

e)
To further clarify (for those who may be interested) - for Oblique Mercator projections, by default, proj.4 performs rectification using the centre of projection (ie +lon_c and +lat_0). However, for all Malaysian datums, old and new, the rectification must be done using the Natural Origin, ie the point where the central line intersects with the Equator, hence the need to also specify +no_off or +no_uoff which instructs proj.4 not to "offset" the point of rectification from Natural Origin to the centre of projection.

**Comment by kbevers** [comment]
@ralphtee Thanks for this clarification. It sounds like you got a good understanding of this projection. Would you be willing to share that knowledge by adding an entry on the oblique mercator  to the documentation?

**Comment by ralphtee** [comment]
@kbevers Yes, I'd gladly assist/contribute for that particular section of the documentation. Please direct yours truly to the website/page for this purpose. Thank you.

**Comment by poidl** [comment]
> Apparently, ogr2ogr (2.2.2) (and presumably gdalwarp as well) ignores +no_rot and will compute a "suitable" gamma value for you if you do not specify +gamma. (Again, discretion is advised.)

Thanks, that makes sense. It would be great to have this in the documentation. It's confusing for newbies.

By the way, I ended up doing sanity checks using geod to calculate distances on the spheroid, see [here](http://sriha.net/articles/computational-grids-for-numerical-ocean-models). Finally I neither used gamma nor no_rot, so I guess ralphtee's quote above applies.

**Comment by kbevers** [comment]
@ralphtee Thanks, that is a big help!

I am assume you are not familiar with the GitHub workflow. If you are, you can skip most of this. You'll need to "fork" the PROJ.4 repository. After you have forked the repository you can then go to your profile and find your copy of the PROJ.4 repository. You are allowed to edit this one. You can do that directly on GitHub by navigating to a file and pushing the pen-symbol in the upper right corner. This should give you a text-editor.

The documentation for `omerc` is in https://github.com/OSGeo/proj.4/blob/master/docs/source/projections/omerc.rst (click the "raw" or "edit" button to see the file without the GitHub rendering).

We write the docs in the Restructured Text format (rst). A good example of how a projection doc page looks is the Mercator: https://github.com/OSGeo/proj.4/blob/master/docs/source/projections/merc.rst

Once you've made your edits you can create a "Pull Request" to the PROJ.4 repository. You can do that from the front page of the PROJ.4 repository.

It shouldn't be too difficult to figure out how this all works, but please let me know if you get stuck somewhere in the process. I'll try to help as best as I can! Thanks once again.

**Comment by DOSull** [comment]
Just posting as this seems to still be an issue.

I've been trying to use an Oblique Mercator in QGIS (3.4). I get similar behaviour in geopandas (0.4), which I used to make the below images showing California when projected using, respectively
    
    +proj=omerc +lonc=-120 +lat_0=37 +alpha=-35 +no_rot

and

    +proj=omerc +lonc=-120 +lat_0=37 +alpha=-35 +gamma=0

![image](https://user-images.githubusercontent.com/8213420/48374885-f895a700-e72a-11e8-833a-15160049ac0d.png)

The first map made with `+no_rot` appears as I would expect with the centre line horizontal, except that the map has been mirrored. The second using `+gamma=0` shows California correctly. 

I suspect that Q and geopandas are using version 4.9.x (not sure how to check this). So in a conda environment at the command line using 5.1.0, I checked and got this:

    proj +proj=omerc +lat_0=0 +lonc=0 +alpha=45 +no_rot
    0 0
    0.00	-0.00
    20 0
    1606867.50	1573685.76
    20 20
    3105093.25	-83150.37
    0 20
    1596329.63	-1563783.66

The counterclockwise quadrilateral (0 0) (20 0) (20 20) (0 20) becomes a clockwise one.  With the `+gamma` option set the quad is not inverted but remains counterclockwise.

I admit my understanding of the details of Oblique Mercator is limited, but this appears that it might be an issue with the code handling the `+no_rot` case. The documentation changes in the above discussion didn't really help this newbie (to oblique mercator) arrive at a solution, except by trial and error. A more direct statement that there are problems with +no_rot would be helpful!

**Comment by ralphtee** [comment]
The short answer:
PROJ.4's `+no_rot` option is working correctly in v4.9.x and v.5.2.0. Unfortunately, the name of the option is a misnomer that had caused much confusion. `+no_rot` doesn't mean "no rotation" - it actually means "no rectification". The mirrored result from `+proj=omerc +lonc=-120 +lat_0=37 +alpha=-35 +no_rot` is correct. 

The long answer:
PROJ.4's `+proj=omerc` follows Snyder's formulas for the Oblique Mercator (OM) projection (see *Map Projections - A Working Manual*). For the expressed purpose of explaining the mirrored result when `+no_rot` is specified, let us group Snyder's OM formulas into three steps - first, from the sphere/ellipsoid to the "aposphere" (1), then to the *uv* plane (2), and finally to the *XY* plane (3). The last step is the *rectification*.

When you specify `+no_rot` in PROJ.4, you see the result of the *uv* plane. It has a perculiar characteristic in that its *v* axis increases downwards, while its *u* axis increases rightwards. This explains the mirror result (ie flipped over the u-axis). Snyder cleverly described it this way
>"... u and v increasing in the directions shown in figure 13". 

(*Clever* because he conveniently avoided "up", "left", "north", "east", and etc. which may confuse the readers.)

![snyder](https://user-images.githubusercontent.com/22031088/48427995-05ef7780-e7a5-11e8-8ef6-681a94fdcce3.jpg)

The figures below shows projected results with and without rectification. (For avoidance of doubt, azimuth is the angle from 12 o'clock clockwise.)

![ab](https://user-images.githubusercontent.com/22031088/48425051-f2411280-e79e-11e8-8b2c-a74c53d75fca.jpg)
![cd](https://user-images.githubusercontent.com/22031088/48425059-f705c680-e79e-11e8-9803-633e564c1653.jpg)

Additional notes:
* Snyder's OM is an improved version of Hotine's Rectified Skew Orthomorphic projection (RSO). Synder simplified it, and introduced several variations. Eg, the central line (CL) in Hotine's RSO is obtained from the centre of projection (COP) and an azimuth through the COP, whereas the CL in Snyder's OM can (also) be obtained by specifying any two points along the intended CL. Rectification in Hotine's RSO must be done only at the Natural Origin (ie at the intersection between the CL and the Equator), but rectification in Snyder's OM can (also) be done at the COP.

* Hotine calls the *uv* coordinates *skewed*, and the *XY* coordinates *rectified* - hence the name of his formula, the *Rectified Skew Orthomorphic* projection. The term *Hotine Oblique Mercator* was first coined by Snyder.

* Rightly-speaking, `+no_rot` should not exist at all because the *uv* result is premature. The final/intended result for the OM/RSO is the *XY* (ie rectified coordinates). Hopefully `+no_rot` can be deprecated soon. Digging through past forum threads hinted that `+no_rot` was a workaround for an erroneous implementation of the Oblique Mercator in the early days of PROJ.4. But since the original problem has long gone, `+no_rot` is now a "problem" itself.

**Comment by DOSull** [comment]
Wow! This is such a great answer. It will take me a while to digest it. It's a pity this level of detail is probably a bit too much for the manual/help! Perhaps a link to this thread could be added.

**Comment by kbevers** [comment]
> It's a pity this level of detail is probably a bit too much for the manual/help!

Nah, I think it is warranted given the multitude of questions regarding this projection. A canonical resource on this is definitely needed.

@ralphtee Thanks once again for elaborating on this. I think it should be possible to digest your answers in this issue down to a useful section in the documentation. When I have some time to spare I will give it a go.
