### ISSUE TITLE
EPSG:25832 equal to EPSG:3044

### ISSUE THREAD

**Issue by tobwen** [OSGeo/PROJ#571]
According to these bug reports, the definitions of _EPSG:25832_ and _EPSG:3044_ equal. These gives several problems on QGIS and other GIS systems using Proj4 definition files.

https://issues.qgis.org/issues/13398
https://issues.qgis.org/issues/17138

Actually, doesn't ETRS89 need a datum? The definition says "European Terrestrial Reference System 1989" as datum, the proj4 string only gives `+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs`.

Should this need anything like _+datum=ETRS89_?

**Comment by rouault** [comment]
Comparing proj.4 strings to infer that 2 CRS are equal isn't going to always work. Regarding this specific issue, GDAL deliberately strips axis information (+axis=) when exporting the WKT coming from the EPSG definition to a proj.4 string. The reason is that datasets, vectors or rasters, that use a EPSG code with a North-East ordering, have the traditional x,y in their data (or if they don't, for example for GML, GDAL will switch the coordinate order), so adding the +axis would result in unexpected behaviour.

proj.4 has a small list of predefined datum names. ETRS89 is not one of those. Not sure of the pros and cons of extending it. Basically for proj, a +datum expands internally either to +ellps= +towgs84= or +ellps= +nadgrids=

**Comment by kbevers** [comment]
> According to these bug reports, the definitions of EPSG:25832 and EPSG:3044 equal

In practice yes, but not in principal. I've previously looked into these, and from memory the difference between the is how the components of the coordinate is ordered. One is xy (25832) the other is yx (3044). I practice in most software the x is always stored the same place and the same for the y. Hence the two become equivalent.

My recommendation is to always use EPSG:25832.

> Actually, doesn't ETRS89 need a datum?

ETRS89 *IS* a datum, also known as a reference frame. ETRS89 is defined to be alligned with WGS84 in the year 1989. Today the two references are off by around 70 cm (ETRS89 moves with the Eurasian plate, WGS84 does not). Historically the two frames have been viewed as equivalent in GIS, which is why the ```+towgs84``` parameters are 0.

> Should this need anything like +datum=ETRS89?

With the above in mind, no. But it would be preferable to have a more precise transformation between WGS84 and ETRS89, which we are currently working on. It does involve time-stamped coordinates however, and most datasets are not born with those, and then we are back to the original no-op transform between WGS84 and ETRS89.

**Comment by tobwen** [comment]
> One is xy (25832) the other is yx (3044). I practice in most software the x is always stored the same place and the same for the y. Hence the two become equivalent.

Yeah, I remember this from lectures: geodetic coordinate systems are rotated. Never thought I would need that in reality :)

> My recommendation is to always use EPSG:25832.

Same here, but QGIS seems to parse the Proj4 parameters and read EPSG:3044 out of it.

> ETRS89 IS a datum, also known as a reference frame. 

Meh, typo - sorry for this. I mean, we should add this information to the Proj4 string - or even the information about switch axis.

> With the above in mind, no. But it would be preferable to have a more precise transformation between WGS84 and ETRS89, which we are currently working on. It does involve time-stamped coordinates however, and most datasets are not born with those, and then we are back to the original no-op transform between WGS84 and ETRS89.

Wow, sounds good. I've been telling people for ages that WGS84 isn't a stable reference system. Most of the people don't know about the different epochs and that parameters exist for shifting the coordinates.

**Comment by kbevers** [comment]
> Yeah, I remember this from lectures: geodetic coordinate systems are rotated. Never thought I would need that in reality :)

These are both projected coordinate system. UTM. 

> Same here, but QGIS seems to parse the Proj4 parameters and read EPSG:3044 out of it.

Actually it is the opposite.

> Wow, sounds good. I've been telling people for ages that WGS84 isn't a stable reference system.   Most of the people don't know about the different epochs and that parameters exist for shifting the coordinates.

In that case the preliminary version of the documentation for the next release of PROJ.4 will be of interest to you. Start here:  https://kbevers.github.io/usage/transformation.html

**Comment by tobwen** [comment]
Closed? Why? We didn't fix the problem :(

**Comment by kbevers** [comment]
I don't really view this as a problem with PROJ.4. The way the various CRS's proj-strings are defined now is a consequence of how various GIS tools treat coordinate systems. PROJ.4 can switch the axis order if you want, but as @rouault said, you'll get unexpected results in your user-faced application.

**Comment by tobwen** [comment]
Okay, I hope the QGIS developers will understand the problems. It's hard to promote the use of open source solutions when such important things fail, but I'll try my best.

**Comment by kbevers** [comment]
> It's hard to promote the use of open source solutions when such important things fail, but I'll try my best.

The problem is broader than that, though. For instance everyones preferred GIS data exchange format, by those who shall not be mentioned, has fixed places for the x, y and z coordinates. The  world is complicated and we can't always fix it. I do think though, that this issue will be solved with time. Better standardisation is most likely the key here, and that trains is already running.

**Comment by rouault** [comment]
The issue and its fix for the specific QGIS issue pointed is probably more mundane. There must be some place where SRS equivalence is done by comparing proj.4 strings, whereas QGIS also maintains EPSG codes that should be used first for that. (I didn't dig, just an intutiton of what the problem might be)

**Comment by tobwen** [comment]
> The problem is broader than that, though. 

I know... I'm trying to give out non-standard GeoJSON (SRS != EPSG:4326) or Geopackage whenever possible. But in 90% of the time, the other users don't know what to do with that :)

**Comment by tobwen** [comment]
> There must be some place where SRS equivalence is done by comparing proj.4 strings, whereas QGIS also maintains EPSG codes that should be used first for that.

QGIS3 will be released soon. Maybe they've touched this part... Let me have a look in the next days.
