### ISSUE TITLE
Improve dmstor.c

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#598]
@cffk commented in a recent post over at #593 that:

> Given that you're improving proj_stdtod.c, how about giving dmstor.c a once over? This has a serious misfeature that the hemisphere designators N,E,W,S, are only used to provide a sign and not to indicate, in addition, latitude vs longitude. Thus a user might specify 45E and have proj.4 treat it like 45N.

I'll take a look in connection with work on #597

**Comment by kbevers** [comment]
Since `dmstor` only reads one value, either a latitude or a longitude, there is not much we can do to change that in the current function. I think the current `dmstor` and `rtodms` functions are sufficient for users of the API. It would however make sense for `proj` and `cs2cs` to be able to distinguish between "25N 80E" and "80E 25N".

**Comment by kbevers** [comment]
`cs2cs` now deals with axis orders other than easting/northing and `proj` is limited to projections where axis ordering isn't such a big deal, so I think theres not much more we can do here.
