### ISSUE TITLE
Memory leaks due to new destructors

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#599]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3568
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3570
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3571
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3572
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3573

have apparently appeared due to the change in destructors ( as the https://github.com/OSGeo/proj.4/compare/0c2f14e53de134e3bdecee45f7bcf9bdb1811432...be3fc4c5d92dc4f42b42792d569289bf6912c0df is identified by cluster fuzz)

**Comment by busstoptaktik** [comment]
Thanks for taking time to compile this list. I'm working on resolving these, and working the way through your list makes the work much easier!

**Comment by busstoptaktik** [comment]
OK - I think I squashed 3568, 3570, 3571, and 3572, which all appeared to be due to PJ_pipeline.c calling the default destructor, rather than the PJ-specific for each individual step.

3573 may be related, but I cannot determine what may be wrong from the stack trace (and I do not have access to a box where I can run the Fuzzer Docker image). So that one will have to wait for some divine inspiration to descend on me :-)

**Comment by rouault** [comment]
> and I do not have access to a box where I can run the Fuzzer Docker image

You don't need to reproduce and fix issues found by oss-fuzz. See https://github.com/OSGeo/proj.4/blob/master/test/fuzzers/README.TXT and the "Build standard_fuzzer in a standalone mode" part

**Comment by busstoptaktik** [comment]
I suspect 3375 may have been resolved through the recent memory handling clean ups by @aaronpuchert

**Comment by busstoptaktik** [comment]
3375 -> 3573

**Comment by rouault** [comment]
I've hopefully addressed the leaks in recent commits

**Comment by busstoptaktik** [comment]
> I've hopefully addressed the leaks in recent commits

Yes, I noticed the update. That was a really nasty bug, and I was quite stuck. Thanks for your effort!
