### ISSUE TITLE
No manpage for cct & gie executables

### ISSUE THREAD

**Issue by sebastic** [OSGeo/PROJ#760]
The new `cct` & `gie` executables have no man pages (in the `man/man1` directory).

This causes the lintian QA tool to report the following warnings:
```
W: proj-bin: binary-without-manpage usr/bin/cct
W: proj-bin: binary-without-manpage usr/bin/gie
```

**Comment by kbevers** [comment]
Thanks for reporting this! On a scale from 1 to 10, how big an offence would it be to not include man-pages for those two applications? I am asking since I'd like to keep things as simple as possible and not maintain several versions documentation. Documentation is severely lacking behind and I prefer to focus the energy on the webpage for now.

**Comment by sebastic** [comment]
I'd say it's an 8, lintian warnings should be fixed in Debian packages.

`help2man` can generate a basic manpage for the commandline options, it mostly needs a description section in addition, optionally an examples section.

**Comment by hobu** [comment]
Sphinx can also generate man pages, but it would be a significant effort to get everything wired up.
