### ISSUE TITLE
Remove proj_api.h as a public header file

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#837]
It has been decided the API in `proj_api.h` will be removed from the library, leaving `proj.h` as the only API in PROJ in version 7.0.0. This will allow us to simplify the internals of PROJ immensely and make library easier to maintain in the future.

What needs to be done:

- [ ] Do not install `proj_api.h` with autotools

- [ ] Do not install `proj_api.h` with CMake

- [ ] Remove references to `proj_api.h` from documentation (website, man-files)

- [ ] ...

**Comment by rouault** [comment]
I think we should re-discuss the opportunity of removing proj_api.h when we have a clearer status on how reverse dependencies have tackled PROJ 6. It is likely that projects that depended on projects.h might directly go to proj.h, but those using proj_api.h might use the ACCEPT_USE_OF_DEPRECATED_PROJ_API_H flag. We should asses the benefits (potential PROJ cleanup) vs costs (delayed adoption of PROJ 7, extra burden for packagers that have already had a good deal with PROJ 6, etc.)

**Comment by hobu** [comment]
>  those using proj_api.h might use the ACCEPT_USE_OF_DEPRECATED_PROJ_API_H flag.

I think this is true. We gave them the ability to kick the can down the road, and they did 😄.

**Comment by busstoptaktik** [comment]
Probably worth considering whether emulating essential parts of proj_api.h on top of proj.h would be worth the effort - if the pareto principle applies, perhaps the 80% solution could be done in 256 LOC?

I'm not saying it is possible, but it might be an economical way of kicking the can further down the road, without  implying a maintenance burden: The semantics of the ACCEPT_USE_OF_yada_yada_yada flag could simply change as of 7.0 to "Yes, I understand that PROJ developers have done their utmost to help me migrate and I'll do my best to squeeze out the last few kinks".

Projects stuck at proj_api.h because of lack of interest/developer resources will suffer the death by bitrot sooner or later anyway.

If not even **trying** to do `sed s/proj_api.h/proj.h/; configure; make all; make test` is feasible, then the relevant project is probably not  viable anyway...
