### ISSUE TITLE
Pipeline doesn't honour +datum=NAD27 expansion to +ellps=clrk66  +nadgrids=@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#872]
The following results in a unexpected no-op
```
$ echo "-100 40 0" | PROJ_LIB=nad src/cct +proj=pipeline +step +proj=longlat +datum=NAD27 +inv +step +proj=longlat +datum=WGS84
-100.0000000000   40.0000000000        0.0000           inf
```
whereas
```
$ echo "-100 40 0" | PROJ_LIB=nad src/cct +proj=pipeline +step +proj=longlat +ellps=clrk66 +nadgrids=@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat +inv +step +proj=longlat +datum=WGS84
-100.0004058367   40.0000058947        0.0000           inf
```
which is the same as
```
$ echo "-100 40 0" | PROJ_LIB=nad src/cs2cs +proj=longlat +datum=NAD27 +to +proj=longlat +datum=WGS84
100d0'1.461"W	40d0'0.021"N 0.000
```

**Comment by kbevers** [comment]
I'll just re-iterate Thomas' explanation of what's going on here: http://lists.maptools.org/pipermail/proj/2018-February/008055.html

The problem can *possibly* be fixed by expanding `+datum=xxx` to it's full representation from `pj_datums` in the top of `cs2cs_emulation_setup()` and adding the expanded parameters to `P->params` before the actual setup is started. Exercise left to the reader :-)

**Comment by kbevers** [comment]
Okay, I think I've got a fix for this. It seems to be straight forward actually. Pull request coming up.
