### ISSUE TITLE
CMakeLists shouldn't unconditionally set -std=c89

### ISSUE THREAD

**Issue by cffk** [OSGeo/PROJ#892]
@aaronpuchert added `-std=c89` to `CMAKE_C_FLAGS` in `CMakeLists.txt` for
the laudable reason to force compliance with the c89 standard.  However
standard compiles should not include this flag -- it makes the
`HAVE_C99_MATH` check fail.  Instead this flag should be added in one of
builds on the CI machines.  I'll note that `configure.ac` doesn't include
this flag so, at present, the cmake and autoconf builds don't use the
same compiler flags.

**Comment by aaronpuchert** [comment]
Someone wrote (not me) that PROJ.4 is developed in C89. The simple fact is that we don't have C99 functions available then. We could decide that PROJ.4 is developed in C99/C11, but must remain (through preprocessor switches) compatible with C89. But do we also run the tests on the C89 builds? Because floating-point functions probably produce different results.

However, I've often had a really hard time reproducing build or test failures because the CI setup is completely different from local builds. I don't like the idea of making them diverge even further. So if anything, we should add an additional CMake profile that builds for C89.

Alternatively, we decide that we work with C99 *exclusively* and create workarounds for compilers that don't support the standard completely. I think the only problematic compiler is MSVC, and they often have underscore-prefixed versions of standard-C99 functions available. So we could add some code for wrapping these, and be done with it.

Actually I would be in favor of that. C89 is truly ancient, in fact it is older than I am. This is the only project I know that still insists on it. After all, it's now almost thirty years old, and there have been two newer standards in the meantime.

**Comment by kbevers** [comment]
> Someone wrote (not me) that PROJ.4 is developed in C89

That was likely me. That fact of the matter is that we *do* write PROJ in C89. I don't think that should prevent us from using C99-functions if they are available though (which they will be almost anywhere I guess).

> However, I've often had a really hard time reproducing build or test failures because the CI setup is completely different from local builds. I don't like the idea of making them diverge even further. So if anything, we should add an additional CMake profile that builds for C89.

I haven't run into that to be honest. What causes these problems for you? Differing `CFLAGS` on your system and the CI setups?

> Actually I would be in favor of that. C89 is truly ancient, in fact it is older than I am. This is the only project I know that still insists on it. After all, it's now almost thirty years old, and there have been two newer standards in the meantime.

I am not opposed to switching to C99 but you'd have to come up with the pretty convincing arguments as to why it is necessary. This is an issue that should be raised on the mailing list if you want to start that discussion. Bear in mind that PROJ is used on *a lot* of different systems ranging from tiny embedded systems to some rather large supercomputing facilities. I am sure that C89 will work across the spectrum. Not so sure about later C versions but it is of course worth looking into if the time has come to ditch C89.

**Comment by aaronpuchert** [comment]
By the way, there is this implementation of `hypot` in `src/hypot.c` but it seems to be used by neither the CMake nor the Autotools build. I can't say if it's used on Windows though.

Technically `hypot` is a C99 function, and @cffk went through the trouble of implementing it in `geodesic.c` as `hypotx`. However it is used far more widely as `hypot`, which can only refer to the standard libraries' implementation then.

**Comment by kbevers** [comment]
The internal `hypot` is used when `HAVE_C99_MATH` is not defined. See the following lines in [projects.h](https://github.com/OSGeo/proj.4/blob/master/src/projects.h#L95-L98):

```
/* prototype hypot for systems where absent */
#if !(defined(HAVE_C99_MATH) && HAVE_C99_MATH)
extern double hypot(double, double);
#endif
```

**Comment by aaronpuchert** [comment]
Yes, but that is only a prototype. The definition in `hypot.c` isn't linked into the library, so it references the standard library instead: compile with `-std=c89` and run `readelf --dyn-syms lib/libproj.so.13.0.1 | grep hypot` on the library. On Linux with GCC I get `hypot@GLIBC_2.2.5` then.

**Comment by kbevers** [comment]
Hmm.. okay. I guess this will be problematic with compilers that are strictly implemented as C89. How do we fix this?

**Comment by cffk** [comment]
Don't -- wait until something breaks!  It seems that libm included hypot before C99 came along and C99 just included the declaration of it.  This isn't the case for all C99 math functions (e.g., atanh).  geodesic.c takes the more cautious approach define a hypot function with a different name.

**Comment by kbevers** [comment]
> Don't -- wait until something breaks!

Well, that is certainly easier! `hypot` must be almost universally available since we haven't had any reports of this being broken. I do remember some times seeing compile time warnings mentioning `hypot` when building with nmake on windows. As far as I remember everything has worked fine though. The warning must be related to this. I'll try to reproduce it when I am at a Windows computer again.
