### ISSUE TITLE
5.0.1 returns inf instead of error

### ISSUE THREAD

**Issue by urschrei** [OSGeo/PROJ#992]
In 5.0.0, the following string would return an error when passed to `PJ_DIRECTION_PJ_FWD` (I had assumed because step 1 isn't an inverse transform, so it was expecting lon and lat input). In 5.0.1 `inf`, `inf` is returned, and `proj_errno` returns 0.

    +proj=pipeline
    +step +proj=lcc +lat_1=33.88333333333333
    +lat_2=32.78333333333333 +lat_0=32.16666666666666
    +lon_0=-116.25 +x_0=2000000.0001016 +y_0=500000.0001016001 +ellps=GRS80
    +towgs84=0,0,0,0,0,0,0 +units=us-ft +no_defs
    +step +proj=lcc +lat_1=33.88333333333333 +lat_2=32.78333333333333 +lat_0=32.16666666666666
    +lon_0=-116.25 +x_0=2000000 +y_0=500000
    +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs

This raises two questions:
1. Is there a semantic difference between `inf`, `inf` and an error value?
2. Could you provide an example string which _should_ return an error when passed to `PJ_DIRECTION_PJ_FWD`, for testing purposes?

**Comment by kbevers** [comment]
> Is there a semantic difference between inf, inf and an error value?

Yes, but usually if you get an `inf` you're probably doing something you shouldn't but it is not detected as an error by PROJ. Here you get an `inf` because you are feeding a projected coordinate (of the order of magnitude 10^5) into a projection that expect input in the range 0--pi. In 5.1 creation of such a pipeline is not allowed.

> Could you provide an example string which should return an error when passed to PJ_DIRECTION_PJ_FWD, for testing purposes?

There are many examples of such strings in the gie test suite: https://github.com/OSGeo/proj.4/tree/master/test/gie 

Grep for "failure" and choose one that suits your purpose.
